export interface WordData {
  word: string;
  hint: string;
  typeHints: string[];
}

export const wordCategories: Record<string, WordData[]> = {
  Allgemein: [
    { word: "Apfel", hint: "wächst am Baum", typeHints: ["süßlich", "knackig", "rund", "essbar"] },
    { word: "Zug", hint: "fährt auf Schienen", typeHints: ["laut", "lang", "pünktlich", "schnell"] },
    { word: "Lampe", hint: "erhellt den Raum", typeHints: ["warm", "hängt oben", "rund", "elektrisch"] },
    { word: "Ball", hint: "wird geworfen oder getreten", typeHints: ["rund", "hüpft", "bunt", "leicht"] },
    { word: "Radio", hint: "spielt Musik ohne Bild", typeHints: ["Stimmen", "Musik", "Nachrichten", "Knöpfe"] },
    { word: "Tisch", hint: "steht auf vier Beinen", typeHints: ["flach", "stabil", "Holz", "groß"] },
    { word: "Auto", hint: "braucht Benzin oder Strom", typeHints: ["schnell", "laut", "Lenkrad", "Räder"] },
    { word: "Handy", hint: "immer dabei", typeHints: ["Bildschirm", "Akku", "Kamera", "klein"] },
    { word: "Hund", hint: "bester Freund des Menschen", typeHints: ["treu", "bellt", "Leine", "Fell"] },
    { word: "Katze", hint: "schläft den halben Tag", typeHints: ["schnurrt", "unabhängig", "Krallen", "leise"] },
    { word: "Mario", hint: "rettet die Prinzessin", typeHints: ["Mütze", "Pilze", "Münzen", "Röhren"] },
    { word: "Deutschland", hint: "Bier und Fußball", typeHints: ["Hauptstadt", "Europa", "Autobahn", "Oktoberfest"] },
    { word: "Pokémon", hint: "du musst sie alle fangen", typeHints: ["Tausch", "Arena", "Entwicklung", "Karten"] },
    { word: "Minecraft", hint: "alles ist ein Block", typeHints: ["Crafting", "Creeper", "Nacht", "Höhle"] },
    { word: "Kühlschrank", hint: "hält Essen frisch", typeHints: ["kalt", "summt", "Tür", "Licht innen"] },
    { word: "Buch", hint: "Papier mit Geschichten", typeHints: ["Seiten", "Regal", "still", "Einband"] },
    { word: "Schuhe", hint: "man trägt sie am Fuß", typeHints: ["Sohle", "Schnürsenkel", "Paar", "Gehen"] },
    { word: "Uhr", hint: "zeigt die Zeit an", typeHints: ["Zeiger", "tickt", "Armband", "rund"] },
    { word: "Brille", hint: "hilft beim Sehen", typeHints: ["Gläser", "Nasensteg", "Bügel", "optisch"] },
    { word: "Schlüssel", hint: "öffnet Türen", typeHints: ["Metall", "klein", "Zähne", "klirrt"] },
    { word: "Rucksack", hint: "trägt man auf dem Rücken", typeHints: ["Reißverschluss", "Schule", "schwer", "Riemen"] },
    { word: "Kerze", hint: "brennt und riecht gut", typeHints: ["Flamme", "Wachs", "Docht", "romantisch"] },
    { word: "Spiegel", hint: "zeigt dein Gesicht", typeHints: ["Reflexion", "Glas", "Badezimmer", "glatt"] },
    { word: "Treppe", hint: "führt nach oben", typeHints: ["Stufen", "Geländer", "steil", "aufwärts"] },
    { word: "Fenster", hint: "man schaut hindurch", typeHints: ["Glas", "Rahmen", "Licht", "offen"] },
    { word: "Sofa", hint: "zum Faulenzen", typeHints: ["weich", "Kissen", "Wohnzimmer", "bequem"] },
    { word: "Laptop", hint: "zum Arbeiten überall", typeHints: ["Tastatur", "Bildschirm", "Akku", "dünn"] },
    { word: "Zahnbürste", hint: "zweimal täglich", typeHints: ["Borsten", "Minze", "Badezimmer", "Stiel"] },
    { word: "Kissen", hint: "Kopf drauf legen", typeHints: ["weich", "Bett", "Füllung", "Überzug"] },
    { word: "Kalender", hint: "zeigt welcher Tag ist", typeHints: ["Monate", "Datum", "Wand", "Woche"] },
    { word: "Feuerzeug", hint: "macht Flamme auf Knopfdruck", typeHints: ["Flamme", "Benzin", "klein", "Klicken"] },
    { word: "Briefkasten", hint: "wartet täglich auf Post", typeHints: ["rot", "Straße", "Schlitz", "Brief"] },
    { word: "Regenschirm", hint: "hält trocken bei Regen", typeHints: ["aufklappen", "rund", "nass", "Wind"] },
    { word: "Koffer", hint: "reist mit einem mit", typeHints: ["Rollen", "Schloss", "packen", "Flughafen"] },
    { word: "Kompass", hint: "zeigt immer Norden", typeHints: ["Nadel", "Norden", "Wandern", "Navigation"] },
    { word: "Lupe", hint: "macht Kleines größer", typeHints: ["Glas", "rund", "Detektiv", "vergrößert"] },
    { word: "Schere", hint: "zwei Klingen die schneiden", typeHints: ["schneiden", "Klingen", "Papier", "Friseur"] },
    { word: "Hammer", hint: "schlägt Nägel ein", typeHints: ["Nagel", "Holz", "schwer", "Werkzeug"] },
    { word: "Sicherheitsnadel", hint: "hält Stoff zusammen ohne zu stechen", typeHints: ["Metall", "spitz", "Kleidung", "Sicherung"] },
    { word: "Würfel", hint: "sechs Seiten Glück", typeHints: ["Punkte", "werfen", "Zufall", "sechs"] },
    { word: "Stempel", hint: "hinterlässt sein Zeichen", typeHints: ["Tinte", "drücken", "Behörde", "rot"] },
    { word: "Notizbuch", hint: "Gedanken festhalten", typeHints: ["Stift", "Zeilen", "klein", "Ideen"] },
    { word: "Magnet", hint: "zieht Metall an", typeHints: ["Haftung", "Nord-Süd", "Kühlschrank", "Eisen"] },
    { word: "Taschenlampe", hint: "Licht im Dunkeln", typeHints: ["Batterien", "Strahl", "Nacht", "Hand"] },
  ],

  Natur: [
    { word: "Baum", hint: "gibt Schatten im Sommer", typeHints: ["Rinde", "Wurzeln", "hoch", "Jahresringe"] },
    { word: "Fluss", hint: "fließt ins Meer", typeHints: ["Strömung", "Ufer", "kalt", "Fische"] },
    { word: "Vogel", hint: "singt am Morgen", typeHints: ["Schnabel", "Federn", "Nest", "Eier"] },
    { word: "Blume", hint: "Bienen lieben sie", typeHints: ["Blütenblätter", "Stiel", "Duft", "Farbe"] },
    { word: "Wolke", hint: "zieht am Himmel vorbei", typeHints: ["weiß", "Regen", "weich", "hoch oben"] },
    { word: "Berg", hint: "manche besteigen ihn", typeHints: ["Gipfel", "steil", "Schnee", "Wandern"] },
    { word: "Sonne", hint: "geht abends unter", typeHints: ["heiß", "Strahlen", "Sommer", "blendet"] },
    { word: "Mond", hint: "leuchtet in der Nacht", typeHints: ["rund", "Phasen", "Ebbe", "still"] },
    { word: "Regen", hint: "macht alles nass", typeHints: ["Tropfen", "grau", "Schirm", "Pfützen"] },
    { word: "Stein", hint: "liegt einfach da", typeHints: ["schwer", "glatt", "kalt", "alt"] },
    { word: "Pilz", hint: "wächst nach dem Regen", typeHints: ["Hut", "Wald", "giftig oder essbar", "Sporen"] },
    { word: "Tornado", hint: "zerstört alles auf seinem Weg", typeHints: ["Wirbel", "laut", "USA", "Trichter"] },
    { word: "Wüste", hint: "heiß am Tag, kalt in der Nacht", typeHints: ["Sand", "Dünen", "trocken", "Kamel"] },
    { word: "Gletscher", hint: "schmilzt gerade", typeHints: ["Eis", "blau", "langsam", "groß"] },
    { word: "Vulkan", hint: "speit Feuer", typeHints: ["Lava", "Asche", "Insel", "heiß"] },
    { word: "Wasserfall", hint: "stürzt in die Tiefe", typeHints: ["laut", "Gischt", "Felsen", "Regenbogen"] },
    { word: "Höhle", hint: "dunkel und feucht", typeHints: ["Stalaktiten", "Fledermäuse", "eng", "Stein"] },
    { word: "Schnee", hint: "kalt und weiß", typeHints: ["Flocken", "Schmelzen", "Winter", "leise"] },
    { word: "Regenbogen", hint: "nach dem Regen", typeHints: ["Farben", "Bogen", "Himmel", "selten"] },
    { word: "Ozean", hint: "größer als alle Kontinente", typeHints: ["salzig", "tief", "Wellen", "blau"] },
    { word: "Insel", hint: "Wasser ringsum", typeHints: ["Palmen", "isoliert", "tropisch", "klein"] },
    { word: "Sumpf", hint: "feucht und moorig", typeHints: ["Schlamm", "Frosch", "grün", "stinkt"] },
    { word: "Klippe", hint: "gefährlicher Abgrund", typeHints: ["hoch", "Meer", "Felsen", "Wind"] },
    { word: "Aurora", hint: "Lichtshow am Nordhimmel", typeHints: ["grün", "Nacht", "Norwegen", "tanzend"] },
    { word: "Tsunami", hint: "riesige Welle", typeHints: ["Erdbeben", "Küste", "Zerstörung", "Ozean"] },
    { word: "Dschungel", hint: "dicht und feucht", typeHints: ["Affen", "Lianen", "heiß", "laut"] },
    { word: "Tundra", hint: "kalt und karg", typeHints: ["Eis", "flach", "Rentiere", "Norden"] },
    { word: "Savanne", hint: "Grasland mit Akazien", typeHints: ["trocken", "Löwen", "Afrika", "weit"] },
    { word: "Korallenriff", hint: "bunte Unterwasserwelt", typeHints: ["Fische", "bunt", "Meer", "empfindlich"] },
    { word: "Blitz", hint: "kommt vor dem Donner", typeHints: ["grell", "kurz", "Gewitter", "gefährlich"] },
  ],

  Sport: [
    { word: "Fußball", hint: "die beliebteste Sportart der Welt", typeHints: ["Elfmeter", "Rasen", "Trikot", "Tor"] },
    { word: "Basketball", hint: "der Korb hängt hoch", typeHints: ["Dribbling", "Sprung", "Halle", "Team"] },
    { word: "Tennis", hint: "Aufschlag und Rückhand", typeHints: ["Netz", "Sandplatz", "Schläger", "Aufschlag"] },
    { word: "Schwimmen", hint: "Kraulen ist am schnellsten", typeHints: ["Bahn", "Chlor", "Brille", "Wende"] },
    { word: "Golf", hint: "weniger Schläge ist besser", typeHints: ["Fairway", "Caddy", "ruhig", "Gras"] },
    { word: "Boxen", hint: "Treffer entscheiden", typeHints: ["Ring", "Handschuhe", "KO", "Runden"] },
    { word: "Skifahren", hint: "Berg runter auf zwei Brettern", typeHints: ["Piste", "Lift", "Helm", "kalt"] },
    { word: "Radfahren", hint: "Pedale treten", typeHints: ["Kette", "Sattel", "Helm", "Berge"] },
    { word: "Volleyball", hint: "der Ball darf nicht den Boden berühren", typeHints: ["Aufschlag", "Netz", "drei Kontakte", "Strand"] },
    { word: "Tischtennis", hint: "winziger Ball, kleines Netz", typeHints: ["Spin", "schnell", "Schläger", "Platte"] },
    { word: "Surfen", hint: "auf der Welle reiten", typeHints: ["Brett", "Ozean", "Balance", "Wellen"] },
    { word: "Turnen", hint: "Kraft und Eleganz", typeHints: ["Barren", "Reck", "Matte", "Pferd"] },
    { word: "Leichtathletik", hint: "Laufen, Springen, Werfen", typeHints: ["Stadion", "Startblock", "Ziellinie", "Medaille"] },
    { word: "Formel 1", hint: "sehr schnelle Autos", typeHints: ["Boxenstopp", "Reifen", "Monaco", "Helm"] },
    { word: "Darts", hint: "Pfeil auf Scheibe", typeHints: ["Bullseye", "180", "Kneipe", "werfen"] },
    { word: "Klettern", hint: "hoch hinaus ohne Motor", typeHints: ["Seil", "Griffe", "Wand", "Sicherung"] },
    { word: "Kampfsport", hint: "Körper als Waffe", typeHints: ["Gürtel", "Technik", "Respekt", "Training"] },
    { word: "Rugby", hint: "wie Fußball aber brutaler", typeHints: ["oval", "tackeln", "Scrum", "Tor"] },
    { word: "Hockey", hint: "mit Schläger auf Eis oder Rasen", typeHints: ["Puck", "Schläger", "Tor", "schnell"] },
    { word: "Handball", hint: "mit den Händen ins Tor", typeHints: ["Wurfarm", "Halle", "7-Meter", "Sprung"] },
    { word: "Bogenschießen", hint: "Pfeil auf Ziel", typeHints: ["Bogen", "Zielscheibe", "ruhig", "Konzentration"] },
    { word: "Triathlon", hint: "drei Sportarten hintereinander", typeHints: ["Schwimmen", "Rad", "Laufen", "Ausdauer"] },
    { word: "Yoga", hint: "Dehnen und Atmen", typeHints: ["Matte", "ruhig", "Positionen", "Gleichgewicht"] },
    { word: "Skateboarden", hint: "Tricks auf Rollen", typeHints: ["Brett", "Rampe", "fallen", "Straße"] },
    { word: "Snowboarden", hint: "ein Brett statt zwei", typeHints: ["Hang", "Sprünge", "Winter", "binden"] },
  ],

  "Essen & Trinken": [
    { word: "Pizza", hint: "kommt aus Italien", typeHints: ["rund", "Ofen", "Käse", "Teig"] },
    { word: "Sushi", hint: "roher Fisch auf Reis", typeHints: ["Essstäbchen", "Japan", "Sojasoße", "Wasabi"] },
    { word: "Burger", hint: "zwischen zwei Brötchenhälften", typeHints: ["Patty", "Ketchup", "Fast Food", "gegrillt"] },
    { word: "Kaffee", hint: "morgens unverzichtbar", typeHints: ["Bohnen", "Espresso", "Milch", "Tasse"] },
    { word: "Bier", hint: "kalt am besten", typeHints: ["Hopfen", "Glas", "Schaum", "Prost"] },
    { word: "Schokolade", hint: "tröstet immer", typeHints: ["Kakao", "süß", "Tafel", "schmelzt"] },
    { word: "Eis", hint: "schmilzt in der Sonne", typeHints: ["Waffel", "Sommer", "Kugel", "kühl"] },
    { word: "Pasta", hint: "al dente ist besser", typeHints: ["Nudeln", "Sauce", "Kochen", "Italien"] },
    { word: "Steak", hint: "medium rare", typeHints: ["Grill", "Messer", "saftig", "Fleisch"] },
    { word: "Smoothie", hint: "Obst im Mixer", typeHints: ["frisch", "bunt", "gesund", "dickflüssig"] },
    { word: "Pommes", hint: "mit Ketchup oder Mayo", typeHints: ["frittiert", "salzig", "Kartoffel", "knusprig"] },
    { word: "Döner", hint: "der Klassiker nach der Party", typeHints: ["Fleisch", "Fladenbrot", "Soße", "Salat"] },
    { word: "Käse", hint: "je älter desto würziger", typeHints: ["Löcher", "Milch", "Rinde", "Frankreich"] },
    { word: "Wein", hint: "aus Trauben gemacht", typeHints: ["Glas", "Weingut", "Jahrgang", "Frankreich"] },
    { word: "Croissant", hint: "zum Frühstück in Paris", typeHints: ["Blätterteig", "Butter", "halbmondförmig", "Bäcker"] },
    { word: "Tacos", hint: "mexikanische Faltentasche", typeHints: ["Tortilla", "Fleisch", "Salsa", "Limette"] },
    { word: "Ramen", hint: "japanische Nudelsuppe", typeHints: ["Brühe", "Ei", "Nudeln", "heiß"] },
    { word: "Cheesecake", hint: "Käsekuchen ohne Käsegeschmack", typeHints: ["cremig", "Keksboden", "Beeren", "Amerika"] },
    { word: "Pancakes", hint: "zum Frühstück mit Sirup", typeHints: ["flach", "stapeln", "Ahornsirup", "weich"] },
    { word: "Nutella", hint: "aus dem Glas löffeln", typeHints: ["Schokolade", "Haselnuss", "braun", "süß"] },
    { word: "Gin Tonic", hint: "mit Gurke garniert", typeHints: ["Glas", "Eis", "bitter", "Cocktail"] },
    { word: "Wasabi", hint: "scharf und grün", typeHints: ["Japan", "Sushi", "brennt", "Paste"] },
    { word: "Avocado", hint: "auf Toast oder in Guacamole", typeHints: ["grün", "cremig", "Kern", "Mexiko"] },
    { word: "Curry", hint: "gelb und scharf", typeHints: ["Gewürze", "Indien", "Reis", "Sauce"] },
    { word: "Latte Macchiato", hint: "Kaffee mit viel Milch", typeHints: ["Schichten", "Glas", "warm", "Schaum"] },
    { word: "Churros", hint: "frittierter Teig mit Zucker", typeHints: ["Spanien", "Schokolade", "süß", "knusprig"] },
    { word: "Fondue", hint: "alles eintauchen", typeHints: ["Käse", "Topf", "Winter", "Schweiz"] },
    { word: "Bagel", hint: "Brot mit Loch", typeHints: ["rund", "Frischkäse", "New York", "sesam"] },
    { word: "Mochi", hint: "klebriger Reiskuchen", typeHints: ["Japan", "weich", "Füllung", "süß"] },
    { word: "Hummus", hint: "Kichererbsenpaste", typeHints: ["Naher Osten", "Pita", "cremig", "Olivenöl"] },
  ],

  "Filme & Serien": [
    { word: "Titanic", hint: "das Schiff sinkt am Ende", typeHints: ["Ozean", "Tragödie", "berühmt", "romantisch"] },
    { word: "Harry Potter", hint: "Magie und eine Narbe", typeHints: ["Zauberstab", "Schule", "Bücher", "Freunde"] },
    { word: "Breaking Bad", hint: "Lehrer wird zum Kriminellen", typeHints: ["Wüste", "Chemie", "Spannung", "Drama"] },
    { word: "Stranger Things", hint: "Kinder gegen das Böse", typeHints: ["80er", "Monster", "Kinder", "übernatürlich"] },
    { word: "Game of Thrones", hint: "jeder Liebling stirbt", typeHints: ["Drachen", "Winter", "Thron", "Intrigen"] },
    { word: "The Office", hint: "Büroalltag als Mockumentary", typeHints: ["Drucker", "Chef", "Witze", "USA"] },
    { word: "Inception", hint: "Traum im Traum", typeHints: ["Ebenen", "Leonardo", "Kreisel", "Realität"] },
    { word: "Avengers", hint: "Superhelden retten die Welt", typeHints: ["Marvel", "Team", "Handschuh", "Kampf"] },
    { word: "Squid Game", hint: "Kinderspiele auf Leben und Tod", typeHints: ["Korea", "Schulden", "Anzug", "Spiele"] },
    { word: "Shrek", hint: "der Held ist ein Oger", typeHints: ["Sumpf", "Esel", "Märchen", "grün"] },
    { word: "Friends (der film)", hint: "sechs Freunde in New York", typeHints: ["Couch", "Café", "Sitcom", "Beziehungen"] },
    { word: "The Lion King", hint: "Hakuna Matata", typeHints: ["Afrika", "König", "Löwe", "Vater"] },
    { word: "Interstellar", hint: "Liebe überwindet Galaxien", typeHints: ["Schwerkraft", "Wormhole", "NASA", "Zeit"] },
    { word: "The Witcher", hint: "Monster jagen für Geld", typeHints: ["Schwert", "Magie", "mittelalterlich", "Mutant"] },
    { word: "Black Mirror", hint: "Technologie als Albtraum", typeHints: ["Zukunft", "Dystopie", "Smartphone", "gruselig"] },
    { word: "Peaky Blinders", hint: "Gangster in Birmingham", typeHints: ["Mütze", "England", "Whisky", "Gewalt"] },
    { word: "Joker", hint: "Clown wird zum Bösewicht", typeHints: ["lacht", "Schminke", "traurig", "Chaos"] },
    { word: "Dune", hint: "Wüstenplanet mit Gewürz", typeHints: ["Sand", "Wurm", "Sci-Fi", "Wasser"] },
    { word: "The Mandalorian", hint: "Baby Yoda", typeHints: ["Rüstung", "Wüste", "Star Wars", "Kopfgeld"] },
    { word: "Euphoria", hint: "Teenagerdrama mit viel Drama", typeHints: ["Schule", "Drogen", "Make-up", "Glitter"] },
    { word: "Money Heist", hint: "Bankraub mit Masken", typeHints: ["rot", "Spanien", "Masken", "Geiseln"] },
    { word: "Wednesday", hint: "düsteres Mädchen in der Schule", typeHints: ["schwarz", "Schule", "gothic", "Familie"] },
    { word: "Gladiator", hint: "kämpf in der Arena", typeHints: ["Rom", "Schild", "Kolosseum", "Ehre"] },
    { word: "Matrix", hint: "alles ist eine Simulation", typeHints: ["rote Pille", "Hacker", "grün", "kämpfen"] },
    { word: "Avatar", hint: "blaue Wesen auf Pandora", typeHints: ["blau", "Wald", "Alien", "3D"] },
  ],

  Musik: [
    { word: "Gitarre", hint: "Rockstars spielen sie", typeHints: ["Saiten", "Griffe", "Plektrum", "Holz"] },
    { word: "Schlagzeug", hint: "lautestes Instrument", typeHints: ["Becken", "Sticks", "Rhythmus", "Takt"] },
    { word: "Klavier", hint: "88 Tasten", typeHints: ["Tasten", "schwarz-weiß", "Konzert", "klassisch"] },
    { word: "Mikrofon", hint: "Stimme wird lauter", typeHints: ["Bühne", "Kabel", "singt rein", "rund"] },
    { word: "Kopfhörer", hint: "Musik nur für dich", typeHints: ["Kabel", "Ohr", "Bass", "Stille außen"] },
    { word: "Drake", hint: "Started from the bottom", typeHints: ["Rap", "Kanada", "Hits", "Studio"] },
    { word: "Beyoncé", hint: "Queen B", typeHints: ["R&B", "Bühne", "Lemonade", "stark"] },
    { word: "Festival", hint: "tagelang Musik unter freiem Himmel", typeHints: ["Zelt", "Schlamm", "Menge", "Bühne"] },
    { word: "Vinyl", hint: "alte Schallplatte", typeHints: ["Nadel", "drehen", "knistern", "Plattenspieler"] },
    { word: "Spotify", hint: "Millionen Songs auf Abruf", typeHints: ["Stream", "Playlist", "Abo", "grün"] },
    { word: "Konzert", hint: "live ist besser als Studio", typeHints: ["Publikum", "Bühne", "Lautsprecher", "Ticket"] },
    { word: "Rap", hint: "Rhythmus und Reime", typeHints: ["Bars", "Beat", "Flow", "Freestyle"] },
    { word: "Bass", hint: "man fühlt ihn mehr als man ihn hört", typeHints: ["tief", "Club", "Subwoofer", "Wumms"] },
    { word: "Taylor Swift", hint: "schreibt Songs über Ex-Freunde", typeHints: ["Pop", "Eras Tour", "Gitarre", "Alben"] },
    { word: "DJ", hint: "legt Platten auf", typeHints: ["Mischpult", "Headphones", "Club", "Crowd"] },
    { word: "Geige", hint: "Streichinstrument mit Bogen", typeHints: ["Orchester", "klassisch", "Bogen", "hoch"] },
    { word: "Flöte", hint: "man bläst quer hinein", typeHints: ["Holz", "Schule", "quer", "hoch"] },
    { word: "Chor", hint: "viele Stimmen gemeinsam", typeHints: ["Kirchenmusik", "Harmonie", "Dirigent", "gemeinsam"] },
  ],

  // ── NEUE KATEGORIEN ────────────────────────────────────────────────────────

  Tiere: [
    { word: "Elefant", hint: "größtes Landtier der Erde", typeHints: ["Rüssel", "Elfenbein", "Afrika", "graue Haut"] },
    { word: "Pinguin", hint: "trägt immer Frack", typeHints: ["Antarktis", "watschelt", "schwimmt", "schwarz-weiß"] },
    { word: "Delfin", hint: "klügste Meerestiere", typeHints: ["Sprung", "Echolot", "Wellen", "verspielt"] },
    { word: "Löwe", hint: "König der Savanne", typeHints: ["Mähne", "brüllt", "Rudel", "Afrika"] },
    { word: "Giraffe", hint: "langer Hals fürs Futter oben", typeHints: ["Flecken", "hoch", "Afrika", "Akazien"] },
    { word: "Koala", hint: "schläft 22 Stunden", typeHints: ["Eukalyptus", "Australien", "flauschig", "Baum"] },
    { word: "Känguru", hint: "Baby im Beutel", typeHints: ["Australien", "hüpft", "Beutel", "boxt"] },
    { word: "Panda", hint: "frisst nur Bambus", typeHints: ["China", "schwarz-weiß", "niedlich", "selten"] },
    { word: "Gorilla", hint: "stärkster Affe", typeHints: ["Brust schlagen", "Regenwald", "mächtig", "Primat"] },
    { word: "Chamäleon", hint: "ändert seine Farbe", typeHints: ["Tarnung", "Augen separat", "langsam", "Zunge"] },
    { word: "Axolotl", hint: "wächst nie so richtig auf", typeHints: ["Mexiko", "Wasser", "rosa", "Kiemen außen"] },
    { word: "Flamingo", hint: "steht auf einem Bein", typeHints: ["rosa", "Wasser", "Schnabel", "Gruppe"] },
    { word: "Pfau", hint: "entfaltet sein Rad zur Schau", typeHints: ["bunt", "Federn", "Rad", "stolz"] },
    { word: "Gepard", hint: "schnellstes Landtier", typeHints: ["Flecken", "sprintet", "schlank", "Afrika"] },
    { word: "Oktopus", hint: "acht Arme, drei Herzen", typeHints: ["Tinte", "Arme", "klug", "Meer"] },
    { word: "Hai", hint: "Film machte alle ängstlich", typeHints: ["Zähne", "Flosse", "Ozean", "Geruch von Blut"] },
    { word: "Adler", hint: "sieht alles von oben", typeHints: ["Krallen", "Schnabel", "hoch", "Majestät"] },
    { word: "Fledermaus", hint: "schläft kopfüber", typeHints: ["Nacht", "Echolot", "Höhle", "Flügel"] },
    { word: "Otter", hint: "schläft auf dem Wasser haltend", typeHints: ["Händchen halten", "Fluss", "Fisch", "verspielt"] },
    { word: "Waschbär", hint: "wäscht sein Essen", typeHints: ["Maske", "Pfoten", "Mülltonne", "nachtaktiv"] },
    { word: "Lama", hint: "spuckt wenn es sauer ist", typeHints: ["Anden", "Wolle", "spuckt", "Lasten"] },
    { word: "Alpaka", hint: "süßere Version des Lamas", typeHints: ["flauschig", "Wolle", "Peru", "Tierpark"] },
    { word: "Biber", hint: "baut Dämme aus Holz", typeHints: ["Zähne", "Schwanz flach", "Fluss", "Holz"] },
    { word: "Nashorn", hint: "Horn auf der Nase", typeHints: ["gepanzert", "Afrika", "selten", "schwer"] },
    { word: "Nilpferd", hint: "aggressivstes Tier Afrikas", typeHints: ["Wasser", "Maul weit auf", "schwer", "grau"] },
    { word: "Schneeleopard", hint: "seltenste Großkatze", typeHints: ["Himalaya", "Flecken", "Bergkette", "selten"] },
    { word: "Kolibri", hint: "fliegt rückwärts", typeHints: ["winzig", "Blüten", "summt", "schnelle Flügel"] },
    { word: "Schildkröte", hint: "trägt ihr Haus", typeHints: ["Panzer", "langsam", "alt", "Meer oder Land"] },
    { word: "Krokodil", hint: "lebt seit Dinos", typeHints: ["Zähne", "Fluss", "lauert", "Panzer"] },
    { word: "Qualle", hint: "kein Gehirn, kein Herz", typeHints: ["Tentakel", "brennt", "schwimmt", "durchsichtig"] },
    { word: "Seepferdchen", hint: "Männchen trägt die Babys aus", typeHints: ["Rüssel", "Meer", "klein", "aufrecht"] },
    { word: "Mantarochen", hint: "fliegt durchs Wasser", typeHints: ["Flügel", "flach", "Ozean", "groß"] },
    { word: "Orang-Utan", hint: "lebt allein im Regenwald", typeHints: ["orange", "Borneo", "klug", "Werkzeug"] },
    { word: "Erdmännchen", hint: "hält Wache für die Gruppe", typeHints: ["aufrecht", "Wüste", "Wachposten", "Clan"] },
  ],

  Berufe: [
    { word: "Feuerwehrmann", hint: "rettet Leben und löscht Brände", typeHints: ["Schlauch", "Leiter", "Helm", "rot"] },
    { word: "Pilot", hint: "bringt dich von A nach B", typeHints: ["Cockpit", "Wolken", "Uniform", "Lizenz"] },
    { word: "Koch", hint: "kreiert Gerichte auf Bestellung", typeHints: ["Schürze", "Messer", "Herd", "Kochhaube"] },
    { word: "Chirurg", hint: "operiert am offenen Körper", typeHints: ["Skalpell", "Handschuhe", "OP-Saal", "präzise"] },
    { word: "Detektiv", hint: "löst Rätsel durch Beobachten", typeHints: ["Lupe", "Notizen", "Verfolgen", "Mantel"] },
    { word: "Astronaut", hint: "verlässt die Erde", typeHints: ["Raumanzug", "Schwerelosigkeit", "Rakete", "NASA"] },
    { word: "Architekt", hint: "entwirft Gebäude auf Papier", typeHints: ["Zeichnung", "Modell", "Maßstab", "Entwurf"] },
    { word: "Zahnarzt", hint: "alle fürchten seinen Stuhl", typeHints: ["Bohrer", "Spiegel", "weit aufmachen", "Schmerzen"] },
    { word: "Tierarzt", hint: "Arzt für alle Vierbeiner", typeHints: ["Tiere", "Spritze", "Stethoskop", "Pfoten"] },
    { word: "Richter", hint: "fällt das letzte Urteil", typeHints: ["Robe", "Hammer", "Gericht", "Gesetz"] },
    { word: "Dirigent", hint: "leitet ohne zu spielen", typeHints: ["Taktstock", "Orchester", "Bühne", "Hände"] },
    { word: "Barkeeper", hint: "mixt deine Träume", typeHints: ["Shaker", "Glas", "Theke", "Cocktail"] },
    { word: "Imker", hint: "züchtet fleißige Insekten", typeHints: ["Schutzanzug", "Rauch", "Honig", "Bienenstock"] },
    { word: "Bestatter", hint: "begleitet den letzten Weg", typeHints: ["Sarg", "still", "schwarz", "Würde"] },
    { word: "Uhrmacher", hint: "gibt der Zeit eine Form", typeHints: ["winzige Teile", "Lupe", "Präzision", "tickt"] },
    { word: "Florist", hint: "macht aus Blumen Kunst", typeHints: ["Sträuße", "Schere", "Duft", "Farben"] },
    { word: "Sommelier", hint: "riecht woran der Wein liegt", typeHints: ["Glas schwenken", "Nase", "Keller", "Jahrgang"] },
    { word: "Ghostwriter", hint: "schreibt für andere, bleibt unsichtbar", typeHints: ["anonym", "Bücher", "Geheimnis", "Feder"] },
    { word: "Vulkanologe", hint: "studiert feuerspeiende Berge", typeHints: ["Lava", "Schutzanzug", "Messgerät", "gefährlich"] },
    { word: "Schlafforscher", hint: "untersucht was nachts passiert", typeHints: ["Elektroden", "Träume", "Labor", "Nacht"] },
    { word: "Gerichtsmediziner", hint: "findet Todesursachen heraus", typeHints: ["Leiche", "Skalpell", "Labor", "Bericht"] },
    { word: "Sprengmeister", hint: "kontrolliertes Zerstören ist seine Kunst", typeHints: ["Zündkabel", "Countdown", "Schutzbrille", "Explosion"] },
    { word: "Museumswächter", hint: "passt auf Kunstwerke auf", typeHints: ["still stehen", "Uniform", "Kunst", "nachts allein"] },
    { word: "Hebamme", hint: "begrüßt neue Menschen", typeHints: ["Geburt", "Krankenhaus", "Vertrauen", "Hände"] },
    { word: "Brauer", hint: "kocht was man trinkt", typeHints: ["Hopfen", "Fass", "Gärung", "Rezept"] },
    { word: "Pathologe", hint: "arbeitet mit denen, die schweigen", typeHints: ["Labor", "Mikroskop", "Gewebe", "Diagnose"] },
  ],

  Orte: [
    { word: "Leuchtturm", hint: "warnt Schiffe vor Felsen", typeHints: ["Licht dreht sich", "Küste", "einsam", "hoch"] },
    { word: "Iglu", hint: "gebaut aus dem was ringsum ist", typeHints: ["Eis", "rund", "warm innen", "Arktis"] },
    { word: "Baumhaus", hint: "Kindheitstraum hoch oben", typeHints: ["Holz", "Leiter", "Äste", "Aussicht"] },
    { word: "Schloss", hint: "adelige lebten hier", typeHints: ["Türme", "Zugbrücke", "Burggraben", "König"] },
    { word: "Raumstation", hint: "schwebt ohne Schwerkraft", typeHints: ["ISS", "Astronauten", "Orbit", "Andocken"] },
    { word: "Bunker", hint: "unter der Erde, sicher vor allem", typeHints: ["Beton", "Kriegszeit", "Stahl", "tief"] },
    { word: "Observatorium", hint: "schaut in die Sterne", typeHints: ["Teleskop", "Kuppel", "Nacht", "Sterne"] },
    { word: "Kasino", hint: "hier kann man alles verlieren", typeHints: ["Chips", "Roulette", "Las Vegas", "Karten"] },
    { word: "Aquarium", hint: "Unterwasserwelt hinter Glas", typeHints: ["Fische", "Tunnel", "Licht", "Haie"] },
    { word: "Planetarium", hint: "Sternenhimmel drinnen", typeHints: ["Projektor", "Kuppel", "Kosmos", "Sitzen"] },
    { word: "Labyrinth", hint: "der Ausweg ist versteckt", typeHints: ["Hecken", "verlaufen", "Mitte", "Rätsel"] },
    { word: "Unterwasserhotel", hint: "schlafen mit Fischen vor dem Fenster", typeHints: ["Meer", "Glas", "Tauchen", "luxuriös"] },
    { word: "Windmühle", hint: "dreht sich wenn Wind weht", typeHints: ["Flügel", "Holz", "Holland", "Mehl"] },
    { word: "Kloster", hint: "Stille und Gebet den ganzen Tag", typeHints: ["Mönche", "Glocken", "Kräuter", "Mauern"] },
    { word: "Festung", hint: "gebaut um Angriffe abzuwehren", typeHints: ["Mauern", "Zinnen", "Kanonen", "alt"] },
    { word: "Piratenschiff", hint: "schwimmt unter schwarzer Flagge", typeHints: ["Totenkopf", "Kanonen", "Ozean", "Schatz"] },
    { word: "Tropfsteinhöhle", hint: "Jahrtausende alte Skulpturen aus Kalk", typeHints: ["tropft", "kalt", "dunkel", "Stalaktiten"] },
    { word: "Wolkenkratzer", hint: "sticht in die Wolken", typeHints: ["Glas", "Fahrstuhl", "Skyline", "hoch"] },
    { word: "Friedhof", hint: "letzte Ruhestätte vieler", typeHints: ["Grabsteine", "still", "Blumen", "Raben"] },
    { word: "Gewächshaus", hint: "Sommer erzwingen im Winter", typeHints: ["Glas", "Pflanzen", "warm", "Feuchtigkeit"] },
    { word: "Bahnhof", hint: "Kommen und Gehen", typeHints: ["Gleise", "Ansage", "Koffer", "Menschenmenge"] },
    { word: "Hafen", hint: "Schiffe kommen und gehen", typeHints: ["Kräne", "Wasser", "Container", "Möwen"] },
    { word: "Marktplatz", hint: "Treffpunkt seit dem Mittelalter", typeHints: ["Stände", "Lärm", "Rathaus", "frisch"] },
    { word: "Stadion", hint: "Zehntausende jubeln gemeinsam", typeHints: ["Rasen", "Tribüne", "Tor", "Flutlicht"] },
  ],

  Technik: [
    { word: "Roboter", hint: "macht was Menschen nicht wollen", typeHints: ["Metall", "Programm", "Fabrik", "Arme"] },
    { word: "Drohne", hint: "fliegt ohne Pilot", typeHints: ["Propeller", "Kamera", "oben", "Fernbedienung"] },
    { word: "Hologramm", hint: "3D-Bild aus Licht", typeHints: ["Projektion", "Sci-Fi", "blau", "greifbar nicht"] },
    { word: "Zeitmaschine", hint: "in Filmen immer kaputt", typeHints: ["Zukunft", "Vergangenheit", "Hebel", "Paradoxon"] },
    { word: "Quantencomputer", hint: "rechnet auf eine neue Art", typeHints: ["Qubits", "kalt", "Forschung", "komplex"] },
    { word: "Exoskelett", hint: "Anzug der Kräfte verleiht", typeHints: ["Metall", "Muskeln", "Militär", "Gehilfe"] },
    { word: "3D-Drucker", hint: "druckt echte Dinge", typeHints: ["Filament", "Schichten", "Plastik", "Modell"] },
    { word: "Jetpack", hint: "Rückenmotor zum Fliegen", typeHints: ["Rücken", "Düsen", "Traum", "Zukunft"] },
    { word: "Smartwatch", hint: "Computer am Handgelenk", typeHints: ["Puls", "Benachrichtigung", "klein", "Armband"] },
    { word: "Biochip", hint: "Technik unter der Haut", typeHints: ["implantiert", "Daten", "Sensor", "Zukunft"] },
    { word: "Hyperloop", hint: "Reisen in der Röhre", typeHints: ["Vakuum", "schnell", "Elon Musk", "Kapsel"] },
    { word: "Augmented Reality", hint: "digitales über die echte Welt legen", typeHints: ["Brille", "Overlays", "Pokémon Go", "Kamera"] },
    { word: "Sprachassistent", hint: "hört immer zu", typeHints: ["Hey Siri", "Lautsprecher", "smart", "Wohnzimmer"] },
    { word: "Selbstfahrendes Auto", hint: "fährt ohne Hände am Steuer", typeHints: ["Sensoren", "Kamera", "KI", "Zukunft"] },
    { word: "Deepfake", hint: "täuschend echte Lüge", typeHints: ["Video", "KI", "Gesicht", "gefälscht"] },
    { word: "Fusionsreaktor", hint: "Energie wie die Sonne", typeHints: ["Plasma", "Hitze", "Forschung", "Zukunft"] },
    { word: "Nanoroboter", hint: "winzige Maschinen im Körper", typeHints: ["Blut", "Medizin", "mikroskopisch", "Heilung"] },
    { word: "Gehirnschnittstelle", hint: "Computer direkt im Kopf", typeHints: ["Neuralink", "Elektroden", "Gedanken", "Zukunft"] },
    { word: "Quantenteleportation", hint: "Information sofort überall", typeHints: ["Physik", "Teilchen", "kein Reisen", "Labor"] },
    { word: "Terraforming", hint: "einen Planeten bewohnbar machen", typeHints: ["Mars", "Atmosphäre", "Jahrtausende", "Sci-Fi"] },
  ],

  Tiere_exotisch: [
    { word: "Axolotl", hint: "sieht aus wie ein Lächeln im Wasser", typeHints: ["Mexiko", "rosa", "Kiemen", "nachwächst"] },
    { word: "Aye-Aye", hint: "gruseligster Finger der Tierwelt", typeHints: ["Madagaskar", "Nacht", "langer Finger", "Auge groß"] },
    { word: "Blobfish", hint: "trauriges Gesicht aus der Tiefsee", typeHints: ["tief", "hässlich", "Meer", "gallertartig"] },
    { word: "Tardigrad", hint: "überlebt selbst im Weltall", typeHints: ["mikroskopisch", "Wasser", "unzerstörbar", "Moostierchen"] },
    { word: "Okapi", hint: "halb Zebra, halb Giraffe", typeHints: ["Streifen", "Regenwald", "selten", "Zunge lang"] },
    { word: "Platypus", hint: "legt Eier obwohl Säugetier", typeHints: ["Schnabel", "Australien", "Schwanz", "giftig"] },
    { word: "Mantis-Garnele", hint: "sieht mehr Farben als alle anderen", typeHints: ["Meer", "bunt", "Schlag", "Augen"] },
    { word: "Pistolengarnele", hint: "Schuss aus der Schere", typeHints: ["Knall", "Wasser", "Schere", "Schall"] },
    { word: "Fossa", hint: "Madagaskars Spitzenräuber", typeHints: ["Madagaskar", "Katze-ähnlich", "Klettern", "selten"] },
    { word: "Quokka", hint: "glücklichstes Tier der Welt", typeHints: ["Australien", "lächelt", "Selfie", "Insel"] },
    { word: "Nasenbär", hint: "langer Rüssel, buschiger Schwanz", typeHints: ["Südamerika", "Rüssel", "neugierig", "Gruppe"] },
    { word: "Binturong", hint: "riecht nach Popcorn", typeHints: ["Asien", "Popcorn-Geruch", "klettern", "buschig"] },
    { word: "Kakapo", hint: "Papagei der nicht fliegen kann", typeHints: ["Neuseeland", "grün", "flugunfähig", "selten"] },
    { word: "Tapir", hint: "lebt wie ein Mini-Nashorn", typeHints: ["Rüssel", "Südamerika", "Wald", "schwimmt"] },
    { word: "Gürteltier", hint: "rollt sich zur Kugel zusammen", typeHints: ["Panzer", "Südamerika", "rollt sich", "gräbt"] },
  ],

  Wissenschaft: [
    { word: "Schwarzes Loch", hint: "saugt alles auf, sogar Licht", typeHints: ["Gravitation", "Ereignishorizont", "Weltall", "unsichtbar"] },
    { word: "DNA", hint: "Bauplan des Lebens", typeHints: ["Doppelhelix", "Gene", "Chromosomen", "Zelle"] },
    { word: "Quantenverschränkung", hint: "zwei Teilchen verbunden über jede Distanz", typeHints: ["Physik", "sofort", "Einstein", "Teilchen"] },
    { word: "Schrödinger-Katze", hint: "tot und lebendig gleichzeitig", typeHints: ["Gedankenexperiment", "Quantenphysik", "Kiste", "Paradoxon"] },
    { word: "Photosynthese", hint: "Pflanzen fressen Licht", typeHints: ["Chlorophyll", "Sauerstoff", "Blätter", "Sonne"] },
    { word: "Biolumineszenz", hint: "Lebewesen leuchten selbst", typeHints: ["Tiefsee", "Glühwürmchen", "blau", "Chemie"] },
    { word: "CRISPR", hint: "Schere für die DNA", typeHints: ["Genbearbeitung", "Labor", "Zukunft", "Ethik"] },
    { word: "Dunkle Materie", hint: "alles ist davon umgeben, niemand sieht es", typeHints: ["unsichtbar", "Universum", "Gravitation", "Rätsel"] },
    { word: "Stringtheorie", hint: "alles ist ein winziger Faden", typeHints: ["Dimensionen", "Physik", "umstritten", "Mathematik"] },
    { word: "Fermi-Paradoxon", hint: "wo sind all die Aliens?", typeHints: ["Weltall", "Intelligenz", "Frage", "Enrico"] },
    { word: "Turing-Test", hint: "kann man Mensch von Maschine unterscheiden?", typeHints: ["KI", "Alan Turing", "Gespräch", "Test"] },
    { word: "Higgs-Boson", hint: "Teilchen das Masse gibt", typeHints: ["CERN", "Beschleuniger", "Gottes Teilchen", "2012"] },
    { word: "Butterfly-Effekt", hint: "kleines Flattern verändert alles", typeHints: ["Chaos", "Wetter", "Schmetterling", "Brasilien"] },
    { word: "Dunning-Kruger-Effekt", hint: "man denkt man weiß mehr als man weiß", typeHints: ["Psychologie", "Selbstüberschätzung", "Experten", "Unwissen"] },
    { word: "Mandela-Effekt", hint: "falsche kollektive Erinnerung", typeHints: ["Erinnerung", "falsch", "viele glauben es", "Internetphänomen"] },
    { word: "Placebo", hint: "wirkt obwohl es nichts enthält", typeHints: ["Pille", "Psyche", "Studie", "Glaube"] },
    { word: "Osmose", hint: "Wasser wandert durch Wände", typeHints: ["Membran", "Konzentration", "Biologie", "Wasser"] },
    { word: "Entropie", hint: "alles wird mit der Zeit chaotischer", typeHints: ["Unordnung", "Zeit", "Energie", "Physik"] },
    { word: "Neutrino", hint: "fliegt durch alles hindurch", typeHints: ["Teilchen", "unsichtbar", "Weltall", "kaum wechselwirkt"] },
    { word: "Gravitationswelle", hint: "Schallwelle durch die Raumzeit", typeHints: ["Einstein", "Kollision", "LIGO", "Welle"] },
  ],

  Emotionen: [
    { word: "Heimweh", hint: "Sehnsucht nach dem vertrauten Ort", typeHints: ["Ferne", "Zuhause", "traurig", "warm"] },
    { word: "Schadenfreude", hint: "deutsches Wort das die Welt kennt", typeHints: ["lachen", "Pech anderer", "gemein", "heimlich"] },
    { word: "Fernweh", hint: "zieht einen in die Weite", typeHints: ["Reisen", "unbekannt", "Koffer", "Horizont"] },
    { word: "Weltschmerz", hint: "der Schmerz über den Zustand der Welt", typeHints: ["Nachrichten", "schwer", "melancholisch", "philosophisch"] },
    { word: "Lampenfieber", hint: "Angst vor dem großen Auftritt", typeHints: ["Bühne", "Herzklopfen", "Schweiß", "Publikum"] },
    { word: "Euphorie", hint: "himmelhoch jauchzend", typeHints: ["Glück", "überwältigend", "Energie", "kurz"] },
    { word: "Melancholie", hint: "tiefer stiller Schmerz", typeHints: ["Regen", "allein", "nachdenklich", "schön und traurig"] },
    { word: "Neid", hint: "will was der andere hat", typeHints: ["grün", "vergleichen", "still", "ungerecht"] },
    { word: "Nostalgie", hint: "süße Trauer über die Vergangenheit", typeHints: ["Erinnerung", "Kindheit", "damals", "warm"] },
    { word: "Empathie", hint: "fühlt was andere fühlen", typeHints: ["Mitgefühl", "verstehen", "zuhören", "verbinden"] },
    { word: "Angst", hint: "kommt ohne Einladung", typeHints: ["Herzklopfen", "Flucht", "Dunkel", "Atem"] },
    { word: "Stolz", hint: "Freude über eigene Leistung", typeHints: ["aufrecht", "Brust raus", "Erfolg", "Eltern"] },
    { word: "Neugier", hint: "will immer mehr wissen", typeHints: ["Fragen", "erkunden", "Kind", "offen"] },
    { word: "Enttäuschung", hint: "wenn Erwartungen nicht erfüllt werden", typeHints: ["hängende Schultern", "still", "gebrochen", "erwartet"] },
    { word: "Überraschung", hint: "man hat es nicht kommen sehen", typeHints: ["Augen auf", "unvorbereitet", "Schock", "Freude"] },
    { word: "Vertrauen", hint: "Grundlage jeder Beziehung", typeHints: ["offen", "ehrlich", "blind", "Stütze"] },
    { word: "Wut", hint: "heiß und laut", typeHints: ["rot", "Fäuste", "Schreien", "Kontrolle"] },
  ],

  Sonstiges: [
    { word: "Zirkus", hint: "Zelt voller Wunder und Artisten", typeHints: ["Manege", "Clown", "Trapez", "Tiere"] },
    { word: "Lügendetektor", hint: "misst Nervosität beim Lügen", typeHints: ["Maschine", "Polizei", "Antwort", "Herzschlag"] },
    { word: "Schwarzmarkt", hint: "illegaler Handel", typeHints: ["verboten", "geheim", "Ware", "Risiko"] },
    { word: "Gerücht", hint: "niemand weiß ob es stimmt", typeHints: ["Flüstern", "Schule", "weitererzählen", "Unsicher"] },
    { word: "Tagebuch", hint: "private Gedanken auf Papier", typeHints: ["Schloss", "geheim", "Stift", "Datum"] },
    { word: "Ritual", hint: "regelmäßige bedeutungsvolle Handlung", typeHints: ["Tradition", "Wiederholung", "bedeutungsvoll", "Gemeinschaft"] },
    { word: "Propaganda", hint: "gezielte Manipulation der Meinung", typeHints: ["Plakate", "Regierung", "einseitig", "Lüge"] },
    { word: "Selbstgespräch", hint: "laut denken", typeHints: ["allein", "Spiegel", "Gedanken", "komisch"] },
    { word: "Spionage", hint: "Geheimnisse stehlen", typeHints: ["geheim", "Mikrofon", "Schatten", "Agent"] },
    { word: "Erpressung", hint: "Geld durch Drohung", typeHints: ["Brief", "drohen", "Schweigen", "Macht"] },
    { word: "Undercover", hint: "verdeckt ermitteln", typeHints: ["Tarnung", "geheim", "Polizei", "Rolle"] },
    { word: "Sabotage", hint: "absichtlich etwas zerstören", typeHints: ["Absicht", "verbergen", "Schaden", "innen"] },
    { word: "Paranoia", hint: "man glaubt alle sind gegen einen", typeHints: ["Misstrauen", "allein", "Gedanken", "angespannt"] },
    { word: "Identitätsdiebstahl", hint: "jemand gibt sich als du aus", typeHints: ["Daten", "Internet", "kriminell", "Schaden"] },
    { word: "Flucht", hint: "raus aus einer gefährlichen Situation", typeHints: ["rennen", "Nacht", "schnell", "Angst"] },
    { word: "Amnestie", hint: "staatliche Begnadigung", typeHints: ["Gnade", "Staat", "Freiheit", "Gesetz"] },
    { word: "Verhör", hint: "intensives Befragen", typeHints: ["Lampe", "Raum", "Fragen", "Druck"] },
    { word: "Alibi", hint: "Beweis der Unschuld", typeHints: ["Zeuge", "Zeit", "Polizei", "Ort"] },
    { word: "Doppelagent", hint: "dient zwei Herren", typeHints: ["geheim", "Verrat", "Spion", "Loyalität"] },
    { word: "Tarnung", hint: "im Verborgenen bleiben", typeHints: ["Camouflage", "unsichtbar", "Natur", "Tier"] },
    { word: "Verdächtiger", hint: "könnte die Tat begangen haben", typeHints: ["Polizei", "Fragen", "Motiv", "Beweise"] },
    { word: "Whistleblower", hint: "deckt Missstände auf", typeHints: ["Mut", "Geheimnis", "enthüllen", "Schutz"] },
    { word: "Maskerade", hint: "verkleidet und unerkannt", typeHints: ["Maske", "Ball", "verkleidet", "geheimnisvoll"] },
    { word: "Detektivroman", hint: "wer hat es getan?", typeHints: ["Mord", "Rätsel", "Sherlock", "Spannung"] },
    { word: "Fluchtplan", hint: "genaue Strategie zum Entkommen", typeHints: ["Karte", "Timing", "Vorbereitung", "geheim"] },
    { word: "Verdacht", hint: "ein ungutes Gefühl", typeHints: ["Misstrauen", "Blick", "leise", "Hinweis"] },
    { word: "Täter", hint: "hat die Tat begangen", typeHints: ["schuldig", "Motiv", "Gericht", "Beweis"] },
    { word: "Zeuge", hint: "hat alles gesehen", typeHints: ["Aussage", "Gericht", "Blick", "wichtig"] },
    { word: "Tresor", hint: "sicherer Behälter für Wertvolles", typeHints: ["Kombination", "Stahl", "Bank", "geheim"] },
    { word: "Doppelleben", hint: "zwei Identitäten gleichzeitig", typeHints: ["geheim", "lügen", "erschöpfend", "riskant"] },
    { word: "Nachtclub", hint: "Tanzen bis zum Morgengrauen", typeHints: ["Licht", "Bass", "Einlass", "Nacht"] },
    { word: "Bande", hint: "Gruppe mit gemeinsamen Zielen", typeHints: ["Zusammenhalt", "Regeln", "Straße", "stark"] },
    { word: "Entführung", hint: "gegen den Willen festgehalten", typeHints: ["Lösegeld", "geheim", "Angst", "suchen"] },
    { word: "Ausweg", hint: "Lösung in einer ausweglosen Situation", typeHints: ["Hoffnung", "Türe", "letzter", "finden"] },
    { word: "Bluff", hint: "überzeugend lügen", typeHints: ["Poker", "riskant", "Gesicht", "täuschen"] },
    { word: "Komplize", hint: "Mitschuldiger", typeHints: ["zusammen", "schuldig", "Teamwork", "Verbrechen"] },
    { word: "Kronzeuge", hint: "wichtigster Zeuge der Anklage", typeHints: ["Schutz", "aussagen", "Gericht", "Schlüssel"] },
    { word: "Magie", hint: "alles scheint möglich", typeHints: ["Zauberstab", "Tricks", "Illusion", "staunen"] },
    { word: "Graffiti", hint: "Kunst oder Vandalismus?", typeHints: ["Wand", "Sprühdose", "bunt", "Straße"] },
    { word: "Tattoo", hint: "permanent auf der Haut", typeHints: ["Nadel", "Tinte", "schmerzt", "dauerhaft"] },
    { word: "Albtraum", hint: "schlechter Traum", typeHints: ["Nacht", "Angst", "schweißgebadet", "Dunkel"] },
    { word: "Déjà-vu", hint: "das Gefühl das schon erlebt zu haben", typeHints: ["Erinnerung", "seltsam", "Moment", "Wiederholung"] },
    { word: "Amnesie", hint: "Gedächtnisverlust", typeHints: ["vergessen", "Unfall", "Identität", "Verwirrung"] },
    { word: "Karma", hint: "was du gibst, kommt zurück", typeHints: ["Schicksal", "Gutes tun", "Hinduismus", "Kreislauf"] },
    { word: "Meditation", hint: "innere Ruhe finden", typeHints: ["Stille", "atmen", "Matte", "Fokus"] },
    { word: "Lotterie", hint: "Glück im Zahlenmeer", typeHints: ["Ticket", "Ziehung", "Millionen", "Zufall"] },
    { word: "Verschwörungstheorie", hint: "andere Erklärung für alles", typeHints: ["Zweifel", "Geheimnis", "YouTube", "Fakten ignorieren"] },
    { word: "Zeitkapsel", hint: "Botschaft für die Zukunft", typeHints: ["vergraben", "Brief", "Nostalgie", "öffnen in 50 Jahren"] },
    { word: "Nostalgie", hint: "Sehnsucht nach früher", typeHints: ["Kindheit", "warm", "Erinnerung", "damals"] },
    { word: "Streik", hint: "Arbeit kollektiv verweigern", typeHints: ["Plakate", "Gewerkschaft", "Lohn", "Protest"] },
    { word: "Cliffhanger", hint: "Serienende das einen nicht loslässt", typeHints: ["Serie", "warten", "Spannung", "offen"] },
    { word: "Ironie", hint: "man meint das Gegenteil", typeHints: ["Witz", "Ton", "Bedeutung", "clever"] },
    { word: "Bucketlist", hint: "Dinge die man vor dem Tod tun will", typeHints: ["Wünsche", "Ziele", "Liste", "Leben"] },
    { word: "Anonymität", hint: "niemand weiß wer du bist", typeHints: ["geheim", "Internet", "Maske", "unerkannt"] },
    { word: "Geheimnis", hint: "darf niemand wissen", typeHints: ["flüstern", "verborgen", "Vertrauen", "still"] },
  ],
};

wordCategories["Alle Wörter"] = Object.entries(wordCategories)
  .filter(([k]) => k !== "Alle Wörter")
  .flatMap(([, v]) => v);

export function pickRandomWord(category: string): WordData {
  const list = wordCategories[category] ?? wordCategories.Allgemein;
  return list[Math.floor(Math.random() * list.length)];
}

export function generateRoomCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "";
  for (let i = 0; i < 6; i++) code += chars[Math.floor(Math.random() * chars.length)];
  return code;
}
