export interface WordData {
  word: string;
  hint: string;
  typeHints: string[];
}

export const wordCategories: Record<string, WordData[]> = {
  Allgemein: [
    { word: "Apfel", hint: "wächst am Baum", typeHints: ["süßlich", "knackig", "rund", "essbar"] },
    { word: "Zug", hint: "fährt auf Schienen", typeHints: ["laut", "lang", "pünktlich", "schnell"] },
    { word: "Lampe", hint: "erhellt den Raum", typeHints: ["warm", "hängt oben", "rund", "elektrisch"] },
    { word: "Ball", hint: "wird geworfen oder getreten", typeHints: ["rund", "hüpft", "bunt", "leicht"] },
    { word: "Radio", hint: "spielt Musik ohne Bild", typeHints: ["Stimmen", "Musik", "Nachrichten", "Knöpfe"] },
    { word: "Tisch", hint: "steht auf vier Beinen", typeHints: ["flach", "stabil", "Holz", "groß"] },
    { word: "Auto", hint: "braucht Benzin oder Strom", typeHints: ["schnell", "laut", "Lenkrad", "Räder"] },
    { word: "Handy", hint: "immer dabei", typeHints: ["Bildschirm", "Akku", "Kamera", "klein"] },
    { word: "Hund", hint: "bester Freund des Menschen", typeHints: ["treu", "bellt", "Leine", "Fell"] },
    { word: "Katze", hint: "schläft den halben Tag", typeHints: ["schnurrt", "unabhängig", "Krallen", "leise"] },
    { word: "Mario", hint: "rettet die Prinzessin", typeHints: ["Mütze", "Pilze", "Münzen", "Röhren"] },
    { word: "Deutschland", hint: "Bier und Fußball", typeHints: ["Hauptstadt", "Europa", "Autobahn", "Oktoberfest"] },
    { word: "Pokémon", hint: "du musst sie alle fangen", typeHints: ["Tausch", "Arena", "Entwicklung", "Karten"] },
    { word: "Minecraft", hint: "alles ist ein Block", typeHints: ["Crafting", "Creeper", "Nacht", "Höhle"] },
    { word: "Kühlschrank", hint: "hält Essen frisch", typeHints: ["kalt", "summt", "Tür", "Licht innen"] },
    { word: "Buch", hint: "Papier mit Geschichten", typeHints: ["Seiten", "Regal", "still", "Einband"] },
    { word: "Schuhe", hint: "man trägt sie am Fuß", typeHints: ["Sohle", "Schnürsenkel", "Paar", "Gehen"] },
    { word: "Uhr", hint: "zeigt die Zeit an", typeHints: ["Zeiger", "tickt", "Armband", "rund"] },
    { word: "Brille", hint: "hilft beim Sehen", typeHints: ["Gläser", "Nasensteg", "Bügel", "optisch"] },
    { word: "Schlüssel", hint: "öffnet Türen", typeHints: ["Metall", "klein", "Zähne", "klirrt"] },
    { word: "Rucksack", hint: "trägt man auf dem Rücken", typeHints: ["Reißverschluss", "Schule", "schwer", "Riemen"] },
    { word: "Kerze", hint: "brennt und riecht gut", typeHints: ["Flamme", "Wachs", "Docht", "romantisch"] },
    { word: "Spiegel", hint: "zeigt dein Gesicht", typeHints: ["Reflexion", "Glas", "Badezimmer", "glatt"] },
    { word: "Treppe", hint: "führt nach oben", typeHints: ["Stufen", "Geländer", "steil", "aufwärts"] },
    { word: "Fenster", hint: "man schaut hindurch", typeHints: ["Glas", "Rahmen", "Licht", "offen"] },
    { word: "Sofa", hint: "zum Faulenzen", typeHints: ["weich", "Kissen", "Wohnzimmer", "bequem"] },
    { word: "Laptop", hint: "zum Arbeiten überall", typeHints: ["Tastatur", "Bildschirm", "Akku", "dünn"] },
    { word: "Zahnbürste", hint: "zweimal täglich", typeHints: ["Borsten", "Minze", "Badezimmer", "Stiel"] },
    { word: "Kissen", hint: "Kopf drauf legen", typeHints: ["weich", "Bett", "Füllung", "Überzug"] },
    { word: "Kalender", hint: "zeigt welcher Tag ist", typeHints: ["Monate", "Datum", "Wand", "Woche"] },
    { word: "Feuerzeug", hint: "macht Flamme auf Knopfdruck", typeHints: ["Flamme", "Benzin", "klein", "Klicken"] },
    { word: "Briefkasten", hint: "wartet täglich auf Post", typeHints: ["rot", "Straße", "Schlitz", "Brief"] },
    { word: "Regenschirm", hint: "hält trocken bei Regen", typeHints: ["aufklappen", "rund", "nass", "Wind"] },
    { word: "Koffer", hint: "reist mit einem mit", typeHints: ["Rollen", "Schloss", "packen", "Flughafen"] },
    { word: "Kompass", hint: "zeigt immer Norden", typeHints: ["Nadel", "Norden", "Wandern", "Navigation"] },
    { word: "Lupe", hint: "macht Kleines größer", typeHints: ["Glas", "rund", "Detektiv", "vergrößert"] },
    { word: "Schere", hint: "zwei Klingen die schneiden", typeHints: ["schneiden", "Klingen", "Papier", "Friseur"] },
    { word: "Hammer", hint: "schlägt Nägel ein", typeHints: ["Nagel", "Holz", "schwer", "Werkzeug"] },
    { word: "Sicherheitsnadel", hint: "hält Stoff zusammen ohne zu stechen", typeHints: ["Metall", "spitz", "Kleidung", "Sicherung"] },
    { word: "Würfel", hint: "sechs Seiten Glück", typeHints: ["Punkte", "werfen", "Zufall", "sechs"] },
    { word: "Stempel", hint: "hinterlässt sein Zeichen", typeHints: ["Tinte", "drücken", "Behörde", "rot"] },
    { word: "Notizbuch", hint: "Gedanken festhalten", typeHints: ["Stift", "Zeilen", "klein", "Ideen"] },
    { word: "Magnet", hint: "zieht Metall an", typeHints: ["Haftung", "Nord-Süd", "Kühlschrank", "Eisen"] },
    { word: "Taschenlampe", hint: "Licht im Dunkeln", typeHints: ["Batterien", "Strahl", "Nacht", "Hand"] },
  ],
  Natur: [
    { word: "Baum", hint: "gibt Schatten im Sommer", typeHints: ["Rinde", "Wurzeln", "hoch", "Jahresringe"] },
    { word: "Fluss", hint: "fließt ins Meer", typeHints: ["Strömung", "Ufer", "kalt", "Fische"] },
    { word: "Vogel", hint: "singt am Morgen", typeHints: ["Schnabel", "Federn", "Nest", "Eier"] },
    { word: "Blume", hint: "Bienen lieben sie", typeHints: ["Blütenblätter", "Stiel", "Duft", "Farbe"] },
    { word: "Wolke", hint: "zieht am Himmel vorbei", typeHints: ["weiß", "Regen", "weich", "hoch oben"] },
    { word: "Berg", hint: "manche besteigen ihn", typeHints: ["Gipfel", "steil", "Schnee", "Wandern"] },
    { word: "Sonne", hint: "geht abends unter", typeHints: ["heiß", "Strahlen", "Sommer", "blendet"] },
    { word: "Mond", hint: "leuchtet in der Nacht", typeHints: ["rund", "Phasen", "Ebbe", "still"] },
    { word: "Regen", hint: "macht alles nass", typeHints: ["Tropfen", "grau", "Schirm", "Pfützen"] },
    { word: "Stein", hint: "liegt einfach da", typeHints: ["schwer", "glatt", "kalt", "alt"] },
    { word: "Pilz", hint: "wächst nach dem Regen", typeHints: ["Hut", "Wald", "giftig oder essbar", "Sporen"] },
    { word: "Tornado", hint: "zerstört alles auf seinem Weg", typeHints: ["Wirbel", "laut", "USA", "Trichter"] },
    { word: "Wüste", hint: "heiß am Tag, kalt in der Nacht", typeHints: ["Sand", "Dünen", "trocken", "Kamel"] },
    { word: "Gletscher", hint: "schmilzt gerade", typeHints: ["Eis", "blau", "langsam", "groß"] },
    { word: "Vulkan", hint: "speit Feuer", typeHints: ["Lava", "Asche", "Insel", "heiß"] },
    { word: "Wasserfall", hint: "stürzt in die Tiefe", typeHints: ["laut", "Gischt", "Felsen", "Regenbogen"] },
    { word: "Höhle", hint: "dunkel und feucht", typeHints: ["Stalaktiten", "Fledermäuse", "eng", "Stein"] },
    { word: "Schnee", hint: "kalt und weiß", typeHints: ["Flocken", "Schmelzen", "Winter", "leise"] },
    { word: "Regenbogen", hint: "nach dem Regen", typeHints: ["Farben", "Bogen", "Himmel", "selten"] },
    { word: "Ozean", hint: "größer als alle Kontinente", typeHints: ["salzig", "tief", "Wellen", "blau"] },
    { word: "Insel", hint: "Wasser ringsum", typeHints: ["Palmen", "isoliert", "tropisch", "klein"] },
    { word: "Sumpf", hint: "feucht und moorig", typeHints: ["Schlamm", "Frosch", "grün", "stinkt"] },
    { word: "Klippe", hint: "gefährlicher Abgrund", typeHints: ["hoch", "Meer", "Felsen", "Wind"] },
    { word: "Aurora", hint: "Lichtshow am Nordhimmel", typeHints: ["grün", "Nacht", "Norwegen", "tanzend"] },
    { word: "Tsunami", hint: "riesige Welle", typeHints: ["Erdbeben", "Küste", "Zerstörung", "Ozean"] },
    { word: "Dschungel", hint: "dicht und feucht", typeHints: ["Affen", "Lianen", "heiß", "laut"] },
    { word: "Tundra", hint: "kalt und karg", typeHints: ["Eis", "flach", "Rentiere", "Norden"] },
    { word: "Savanne", hint: "Grasland mit Akazien", typeHints: ["trocken", "Löwen", "Afrika", "weit"] },
    { word: "Korallenriff", hint: "bunte Unterwasserwelt", typeHints: ["Fische", "bunt", "Meer", "empfindlich"] },
    { word: "Blitz", hint: "kommt vor dem Donner", typeHints: ["grell", "kurz", "Gewitter", "gefährlich"] },
  ],
  Sport: [
    { word: "Fußball", hint: "die beliebteste Sportart der Welt", typeHints: ["Elfmeter", "Rasen", "Trikot", "Tor"] },
    { word: "Basketball", hint: "der Korb hängt hoch", typeHints: ["Dribbling", "Sprung", "Halle", "Team"] },
    { word: "Tennis", hint: "Aufschlag und Rückhand", typeHints: ["Netz", "Sandplatz", "Schläger", "Aufschlag"] },
    { word: "Schwimmen", hint: "Kraulen ist am schnellsten", typeHints: ["Bahn", "Chlor", "Brille", "Wende"] },
    { word: "Golf", hint: "weniger Schläge ist besser", typeHints: ["Fairway", "Caddy", "ruhig", "Gras"] },
    { word: "Boxen", hint: "Treffer entscheiden", typeHints: ["Ring", "Handschuhe", "KO", "Runden"] },
    { word: "Skifahren", hint: "Berg runter auf zwei Brettern", typeHints: ["Piste", "Lift", "Helm", "kalt"] },
    { word: "Radfahren", hint: "Pedale treten", typeHints: ["Kette", "Sattel", "Helm", "Berge"] },
    { word: "Volleyball", hint: "der Ball darf nicht den Boden berühren", typeHints: ["Aufschlag", "Netz", "drei Kontakte", "Strand"] },
    { word: "Tischtennis", hint: "winziger Ball, kleines Netz", typeHints: ["Spin", "schnell", "Schläger", "Platte"] },
    { word: "Surfen", hint: "auf der Welle reiten", typeHints: ["Brett", "Ozean", "Balance", "Wellen"] },
    { word: "Turnen", hint: "Kraft und Eleganz", typeHints: ["Barren", "Reck", "Matte", "Pferd"] },
    { word: "Leichtathletik", hint: "Laufen, Springen, Werfen", typeHints: ["Stadion", "Startblock", "Ziellinie", "Medaille"] },
    { word: "Formel 1", hint: "sehr schnelle Autos", typeHints: ["Boxenstopp", "Reifen", "Monaco", "Helm"] },
    { word: "Darts", hint: "Pfeil auf Scheibe", typeHints: ["Bullseye", "180", "Kneipe", "werfen"] },
    { word: "Klettern", hint: "hoch hinaus ohne Motor", typeHints: ["Seil", "Griffe", "Wand", "Sicherung"] },
    { word: "Kampfsport", hint: "Körper als Waffe", typeHints: ["Gürtel", "Technik", "Respekt", "Training"] },
    { word: "Rugby", hint: "wie Fußball aber brutaler", typeHints: ["oval", "tackeln", "Scrum", "Tor"] },
    { word: "Hockey", hint: "mit Schläger auf Eis oder Rasen", typeHints: ["Puck", "Schläger", "Tor", "schnell"] },
    { word: "Handball", hint: "mit den Händen ins Tor", typeHints: ["Wurfarm", "Halle", "7-Meter", "Sprung"] },
    { word: "Bogenschießen", hint: "Pfeil auf Ziel", typeHints: ["Bogen", "Zielscheibe", "ruhig", "Konzentration"] },
    { word: "Triathlon", hint: "drei Sportarten hintereinander", typeHints: ["Schwimmen", "Rad", "Laufen", "Ausdauer"] },
    { word: "Yoga", hint: "Dehnen und Atmen", typeHints: ["Matte", "ruhig", "Positionen", "Gleichgewicht"] },
    { word: "Skateboarden", hint: "Tricks auf Rollen", typeHints: ["Brett", "Rampe", "fallen", "Straße"] },
    { word: "Snowboarden", hint: "ein Brett statt zwei", typeHints: ["Hang", "Sprünge", "Winter", "binden"] },
  ],
  "Essen & Trinken": [
    { word: "Pizza", hint: "kommt aus Italien", typeHints: ["rund", "Ofen", "Käse", "Teig"] },
    { word: "Sushi", hint: "roher Fisch auf Reis", typeHints: ["Essstäbchen", "Japan", "Sojasoße", "Wasabi"] },
    { word: "Burger", hint: "zwischen zwei Brötchenhälften", typeHints: ["Patty", "Ketchup", "Fast Food", "gegrillt"] },
    { word: "Kaffee", hint: "morgens unverzichtbar", typeHints: ["Bohnen", "Espresso", "Milch", "Tasse"] },
    { word: "Bier", hint: "kalt am besten", typeHints: ["Hopfen", "Glas", "Schaum", "Prost"] },
    { word: "Schokolade", hint: "tröstet immer", typeHints: ["Kakao", "süß", "Tafel", "schmelzt"] },
    { word: "Eis", hint: "schmilzt in der Sonne", typeHints: ["Waffel", "Sommer", "Kugel", "kühl"] },
    { word: "Pasta", hint: "al dente ist besser", typeHints: ["Nudeln", "Sauce", "Kochen", "Italien"] },
    { word: "Steak", hint: "medium rare", typeHints: ["Grill", "Messer", "saftig", "Fleisch"] },
    { word: "Smoothie", hint: "Obst im Mixer", typeHints: ["frisch", "bunt", "gesund", "dickflüssig"] },
    { word: "Pommes", hint: "mit Ketchup oder Mayo", typeHints: ["frittiert", "salzig", "Kartoffel", "knusprig"] },
    { word: "Döner", hint: "der Klassiker nach der Party", typeHints: ["Fleisch", "Fladenbrot", "Soße", "Salat"] },
    { word: "Käse", hint: "je älter desto würziger", typeHints: ["Löcher", "Milch", "Rinde", "Frankreich"] },
    { word: "Wein", hint: "aus Trauben gemacht", typeHints: ["Glas", "Weingut", "Jahrgang", "Frankreich"] },
    { word: "Croissant", hint: "zum Frühstück in Paris", typeHints: ["Blätterteig", "Butter", "halbmondförmig", "Bäcker"] },
    { word: "Tacos", hint: "mexikanische Faltentasche", typeHints: ["Tortilla", "Fleisch", "Salsa", "Limette"] },
    { word: "Ramen", hint: "japanische Nudelsuppe", typeHints: ["Brühe", "Ei", "Nudeln", "heiß"] },
    { word: "Cheesecake", hint: "Käsekuchen ohne Käsegeschmack", typeHints: ["cremig", "Keksboden", "Beeren", "Amerika"] },
    { word: "Pancakes", hint: "zum Frühstück mit Sirup", typeHints: ["flach", "stapeln", "Ahornsirup", "weich"] },
    { word: "Nutella", hint: "aus dem Glas löffeln", typeHints: ["Schokolade", "Haselnuss", "braun", "süß"] },
    { word: "Gin Tonic", hint: "mit Gurke garniert", typeHints: ["Glas", "Eis", "bitter", "Cocktail"] },
    { word: "Wasabi", hint: "scharf und grün", typeHints: ["Japan", "Sushi", "brennt", "Paste"] },
    { word: "Avocado", hint: "auf Toast oder in Guacamole", typeHints: ["grün", "cremig", "Kern", "Mexiko"] },
    { word: "Curry", hint: "gelb und scharf", typeHints: ["Gewürze", "Indien", "Reis", "Sauce"] },
    { word: "Latte Macchiato", hint: "Kaffee mit viel Milch", typeHints: ["Schichten", "Glas", "warm", "Schaum"] },
    { word: "Churros", hint: "frittierter Teig mit Zucker", typeHints: ["Spanien", "Schokolade", "süß", "knusprig"] },
    { word: "Fondue", hint: "alles eintauchen", typeHints: ["Käse", "Topf", "Winter", "Schweiz"] },
    { word: "Bagel", hint: "Brot mit Loch", typeHints: ["rund", "Frischkäse", "New York", "sesam"] },
    { word: "Mochi", hint: "klebriger Reiskuchen", typeHints: ["Japan", "weich", "Füllung", "süß"] },
    { word: "Hummus", hint: "Kichererbsenpaste", typeHints: ["Naher Osten", "Pita", "cremig", "Olivenöl"] },
  ],
  "Filme & Serien": [
    { word: "Titanic", hint: "das Schiff sinkt am Ende", typeHints: ["Ozean", "Tragödie", "berühmt", "romantisch"] },
    { word: "Harry Potter", hint: "Magie und eine Narbe", typeHints: ["Zauberstab", "Schule", "Bücher", "Freunde"] },
    { word: "Breaking Bad", hint: "Lehrer wird zum Kriminellen", typeHints: ["Wüste", "Chemie", "Spannung", "Drama"] },
    { word: "Der Pate", hint: "Angebot das man nicht ablehnen kann", typeHints: ["Mafia", "Familie", "Macht", "Anzug"] },
    { word: "Stranger Things", hint: "Kinder gegen das Böse", typeHints: ["80er", "Monster", "Kinder", "übernatürlich"] },
    { word: "Game of Thrones", hint: "jeder Liebling stirbt", typeHints: ["Drachen", "Winter", "Thron", "Intrigen"] },
    { word: "The Office", hint: "Büroalltag als Mockumentary", typeHints: ["Drucker", "Chef", "Witze", "USA"] },
    { word: "Inception", hint: "Traum im Traum", typeHints: ["Ebenen", "Leonardo", "Kreisel", "Realität"] },
    { word: "Avengers", hint: "Superhelden retten die Welt", typeHints: ["Marvel", "Team", "Handschuh", "Kampf"] },
    { word: "Squid Game", hint: "Kinderspiele auf Leben und Tod", typeHints: ["Korea", "Schulden", "Anzug", "Spiele"] },
    { word: "Pulp Fiction", hint: "nicht chronologisch erzählt", typeHints: ["Koffer", "Tarantino", "tanzen", "Dialog"] },
    { word: "The Lion King", hint: "Hakuna Matata", typeHints: ["Afrika", "König", "Löwe", "Vater"] },
    { word: "Interstellar", hint: "Liebe überwindet Galaxien", typeHints: ["Schwerkraft", "Wormhole", "NASA", "Zeit"] },
    { word: "Parasite", hint: "Arm trifft Reich", typeHints: ["Korea", "Keller", "Spannung", "Klassen"] },
    { word: "The Witcher", hint: "Monster jagen für Geld", typeHints: ["Schwert", "Magie", "mittelalterlich", "Mutant"] },
    { word: "Black Mirror", hint: "Technologie als Albtraum", typeHints: ["Zukunft", "Dystopie", "Smartphone", "gruselig"] },
    { word: "Peaky Blinders", hint: "Gangster in Birmingham", typeHints: ["Mütze", "England", "Whisky", "Gewalt"] },
    { word: "Joker", hint: "Clown wird zum Bösewicht", typeHints: ["lacht", "Schminke", "traurig", "Chaos"] },
    { word: "Dune", hint: "Wüstenplanet mit Gewürz", typeHints: ["Sand", "Wurm", "Sci-Fi", "Wasser"] },
    { word: "The Mandalorian", hint: "Baby Yoda", typeHints: ["Rüstung", "Wüste", "Star Wars", "Kopfgeld"] },
    { word: "Euphoria", hint: "Teenagerdrama mit viel Drama", typeHints: ["Schule", "Drogen", "Make-up", "Glitter"] },
    { word: "Money Heist", hint: "Bankraub mit Masken", typeHints: ["rot", "Spanien", "Masken", "Geiseln"] },
    { word: "Wednesday", hint: "düsteres Mädchen in der Schule", typeHints: ["schwarz", "Schule", "gothic", "Familie"] },
    { word: "Gladiator", hint: "kämpf in der Arena", typeHints: ["Rom", "Schild", "Kolosseum", "Ehre"] },
    { word: "Forrest Gump", hint: "Leben ist wie eine Schachtel Pralinen", typeHints: ["laufen", "Amerika", "Geschichte", "einfach"] },
    { word: "Matrix", hint: "alles ist eine Simulation", typeHints: ["rote Pille", "Hacker", "grün", "kämpfen"] },
    { word: "Avatar", hint: "blaue Wesen auf Pandora", typeHints: ["blau", "Wald", "Alien", "3D"] },
  ],
  Berufe: [
    { word: "Arzt", hint: "Stethoskop um den Hals", typeHints: ["Patienten", "Krankenhaus", "Diagnose", "Studium"] },
    { word: "Lehrer", hint: "schreibt an die Tafel", typeHints: ["Klasse", "Noten", "Ferien", "Schüler"] },
    { word: "Koch", hint: "trägt eine weiße Mütze", typeHints: ["Herd", "Messer", "Rezept", "Restaurant"] },
    { word: "Pilot", hint: "fliegt über Wolken", typeHints: ["Cockpit", "Uniform", "Flughafen", "Höhe"] },
    { word: "Feuerwehrmann", hint: "löscht Brände", typeHints: ["Schlauch", "Leiter", "Helm", "rot"] },
    { word: "Polizist", hint: "hält Ordnung", typeHints: ["Uniform", "Handschellen", "Streife", "Blaulicht"] },
    { word: "Architekt", hint: "entwirft Gebäude", typeHints: ["Pläne", "Modell", "Konstruktion", "Design"] },
    { word: "Journalist", hint: "schreibt für die Zeitung", typeHints: ["Mikrofon", "Recherche", "Schreibtisch", "Deadline"] },
    { word: "Programmierer", hint: "spricht mit dem Computer", typeHints: ["Code", "Tastatur", "Fehler", "Nacht"] },
    { word: "Anwalt", hint: "verteidigt vor Gericht", typeHints: ["Akten", "Gericht", "Anzug", "Gesetz"] },
    { word: "Zahnarzt", hint: "alle fürchten ihn", typeHints: ["Bohrer", "Zähne", "Stuhl", "Mundspülung"] },
    { word: "Astronaut", hint: "war im Weltall", typeHints: ["Rakete", "schwerelos", "Anzug", "Sauerstoff"] },
    { word: "Bäcker", hint: "steht um 4 Uhr auf", typeHints: ["Ofen", "Teig", "Brot", "früh"] },
    { word: "Tierarzt", hint: "behandelt keine Menschen", typeHints: ["Tiere", "Impfung", "Fell", "Praxis"] },
    { word: "Schauspieler", hint: "spielt jemand anderen", typeHints: ["Bühne", "Rolle", "Text", "Applaus"] },
    { word: "Fotograf", hint: "hält Momente fest", typeHints: ["Kamera", "Objektiv", "Blitz", "Bild"] },
    { word: "Chirurg", hint: "operiert am offenen Körper", typeHints: ["Skalpell", "Handschuhe", "OP-Saal", "steril"] },
    { word: "Detektiv", hint: "löst Fälle", typeHints: ["Lupe", "Spuren", "Verdächtiger", "geheim"] },
    { word: "Tätowierer", hint: "zeichnet permanent auf Haut", typeHints: ["Nadel", "Tinte", "schmerzt", "dauerhaft"] },
    { word: "Influencer", hint: "macht Fotos für Follower", typeHints: ["Instagram", "Selfie", "Werbung", "online"] },
    { word: "Sommelier", hint: "kennt jeden Wein", typeHints: ["Weinglas", "riechen", "Jahrgang", "Restaurant"] },
    { word: "Bergführer", hint: "bringt dich sicher auf den Gipfel", typeHints: ["Seil", "Karte", "Höhe", "Alpen"] },
    { word: "Hacker", hint: "bricht in Systeme ein", typeHints: ["Code", "schwarz", "geheim", "Computer"] },
    { word: "Hebamme", hint: "hilft bei der Geburt", typeHints: ["Krankenhaus", "Baby", "Frau", "Geburt"] },
    { word: "Diplomat", hint: "verhandelt zwischen Ländern", typeHints: ["Botschaft", "Sprachen", "Anzug", "Verhandlung"] },
    { word: "Puppenspieler", hint: "leiht Figuren seine Stimme", typeHints: ["Fäden", "Bühne", "Kind", "Holz"] },
    { word: "Bestatter", hint: "kümmert sich um das letzte Geleit", typeHints: ["Sarg", "ruhig", "schwarz", "Friedhof"] },
    { word: "Imker", hint: "hält Bienen", typeHints: ["Honig", "Stich", "Schutzanzug", "Waben"] },
    { word: "Uhrmacher", hint: "repariert präzise Uhrwerke", typeHints: ["Zahnräder", "Lupe", "fein", "Zeit"] },
    { word: "Dompteur", hint: "zähmt wilde Tiere", typeHints: ["Peitsche", "Zirkus", "Mut", "Löwe"] },
    { word: "Richter", hint: "fällt das letzte Urteil", typeHints: ["Robe", "Hammer", "Gericht", "Gesetz"] },
    { word: "Dirigent", hint: "leitet ohne zu spielen", typeHints: ["Taktstock", "Orchester", "Bühne", "Hände"] },
    { word: "Barkeeper", hint: "mixt deine Träume", typeHints: ["Shaker", "Glas", "Theke", "Cocktail"] },
    { word: "Florist", hint: "macht aus Blumen Kunst", typeHints: ["Sträuße", "Schere", "Duft", "Farben"] },
    { word: "Ghostwriter", hint: "schreibt für andere, bleibt unsichtbar", typeHints: ["anonym", "Bücher", "Geheimnis", "Feder"] },
    { word: "Vulkanologe", hint: "studiert feuerspeiende Berge", typeHints: ["Lava", "Schutzanzug", "Messgerät", "gefährlich"] },
    { word: "Schlafforscher", hint: "untersucht was nachts passiert", typeHints: ["Elektroden", "Träume", "Labor", "Nacht"] },
    { word: "Gerichtsmediziner", hint: "findet Todesursachen heraus", typeHints: ["Leiche", "Skalpell", "Labor", "Bericht"] },
    { word: "Sprengmeister", hint: "kontrolliertes Zerstören ist seine Kunst", typeHints: ["Zündkabel", "Countdown", "Schutzbrille", "Explosion"] },
    { word: "Museumswächter", hint: "passt auf Kunstwerke auf", typeHints: ["still stehen", "Uniform", "Kunst", "nachts allein"] },
    { word: "Brauer", hint: "kocht was man trinkt", typeHints: ["Hopfen", "Fass", "Gärung", "Rezept"] },
    { word: "Pathologe", hint: "arbeitet mit denen, die schweigen", typeHints: ["Labor", "Mikroskop", "Gewebe", "Diagnose"] },
  ],
  Orte: [
    { word: "Strand", hint: "Sand zwischen den Zehen", typeHints: ["Wellen", "Sonne", "Muscheln", "Urlaub"] },
    { word: "Supermarkt", hint: "Einkaufswagen schieben", typeHints: ["Kasse", "Regal", "Angebot", "Tüte"] },
    { word: "Flughafen", hint: "Koffer und Wartezeit", typeHints: ["Gate", "Sicherheit", "Terminal", "Abflug"] },
    { word: "Bibliothek", hint: "hier ist es leise", typeHints: ["Regale", "Bücher", "flüstern", "ausleihen"] },
    { word: "Krankenhaus", hint: "man will schnell wieder raus", typeHints: ["weiß", "Betten", "Ärzte", "Flur"] },
    { word: "Schule", hint: "Pflicht bis 18", typeHints: ["Klassen", "Glocke", "Tafel", "Pausen"] },
    { word: "Fitnessstudio", hint: "Schweiß und Spiegel", typeHints: ["Hanteln", "Geräte", "Muskeln", "Abo"] },
    { word: "Zoo", hint: "Tiere hinter Gittern", typeHints: ["Gehege", "Kinder", "Fütterung", "Löwen"] },
    { word: "Museum", hint: "alles darf man nicht anfassen", typeHints: ["Ausstellung", "still", "Kunst", "Geschichte"] },
    { word: "Kino", hint: "Popcorn und große Leinwand", typeHints: ["dunkel", "Sitz", "Film", "Trailers"] },
    { word: "Bahnhof", hint: "Züge kommen und gehen", typeHints: ["Gleis", "Ansage", "Koffer", "Verspätung"] },
    { word: "Restaurant", hint: "jemand anderes kocht", typeHints: ["Speisekarte", "Kellner", "Tisch", "Trinkgeld"] },
    { word: "Friedhof", hint: "stille Ruhe", typeHints: ["Grabstein", "Blumen", "Bäume", "Trauer"] },
    { word: "Disco", hint: "Musik und Tanzen bis in den Morgen", typeHints: ["Licht", "Menge", "Bass", "Nacht"] },
    { word: "Gefängnis", hint: "man will nicht rein", typeHints: ["Gitter", "Zelle", "Wächter", "Strafe"] },
    { word: "Marktplatz", hint: "Treffpunkt der Stadt", typeHints: ["Stände", "laut", "frisch", "Mitte"] },
    { word: "Kasino", hint: "Glück entscheidet", typeHints: ["Roulette", "Chips", "Anzug", "Las Vegas"] },
    { word: "Aquarium", hint: "Fische hinter Glas", typeHints: ["Unterwasser", "blau", "still", "Haie"] },
    { word: "Schwimmbad", hint: "Bahn ziehen oder plantschen", typeHints: ["Chlor", "Rutsche", "nass", "Bahnen"] },
    { word: "Einkaufszentrum", hint: "alles unter einem Dach", typeHints: ["Rolltreppen", "Shops", "Parkhaus", "voll"] },
    { word: "Kirche", hint: "Glocken läuten am Sonntag", typeHints: ["Turm", "Glaube", "ruhig", "Kerzen"] },
    { word: "Stadion", hint: "tausende Fans auf einem Haufen", typeHints: ["Rasen", "Tribüne", "Tor", "laut"] },
    { word: "Hafen", hint: "Schiffe laden und löschen", typeHints: ["Kräne", "Wasser", "Container", "Mole"] },
    { word: "Dachboden", hint: "voller alter Erinnerungen", typeHints: ["staubig", "Kisten", "heiß", "vergessen"] },
    { word: "Bunker", hint: "Schutz unter der Erde", typeHints: ["Beton", "dunkel", "tief", "Krieg"] },
    { word: "Leuchtturm", hint: "warnt Schiffe vor Felsen", typeHints: ["Licht", "Küste", "hoch", "einsam"] },
    { word: "Raumschiff", hint: "fliegt durch das Weltall", typeHints: ["schwerelos", "Crew", "Rakete", "fern"] },
    { word: "Iglu", hint: "Haus aus Schnee", typeHints: ["Eis", "rund", "Inuit", "warm innen"] },
    { word: "Schloss", hint: "König und Königin wohnten darin", typeHints: ["Türme", "alt", "Graben", "Europa"] },
    { word: "Untergrundbahn", hint: "fährt unter der Stadt", typeHints: ["U-Bahn", "Tunnel", "Schienen", "voll"] },
    { word: "Baumhaus", hint: "Kindheitstraum hoch oben", typeHints: ["Holz", "Leiter", "Äste", "Aussicht"] },
    { word: "Raumstation", hint: "schwebt ohne Schwerkraft", typeHints: ["ISS", "Astronauten", "Orbit", "Andocken"] },
    { word: "Observatorium", hint: "schaut in die Sterne", typeHints: ["Teleskop", "Kuppel", "Nacht", "Sterne"] },
    { word: "Planetarium", hint: "Sternenhimmel drinnen", typeHints: ["Projektor", "Kuppel", "Kosmos", "Sitzen"] },
    { word: "Labyrinth", hint: "der Ausweg ist versteckt", typeHints: ["Hecken", "verlaufen", "Mitte", "Rätsel"] },
    { word: "Windmühle", hint: "dreht sich wenn Wind weht", typeHints: ["Flügel", "Holz", "Holland", "Mehl"] },
    { word: "Kloster", hint: "Stille und Gebet den ganzen Tag", typeHints: ["Mönche", "Glocken", "Kräuter", "Mauern"] },
    { word: "Festung", hint: "gebaut um Angriffe abzuwehren", typeHints: ["Mauern", "Zinnen", "Kanonen", "alt"] },
    { word: "Piratenschiff", hint: "schwimmt unter schwarzer Flagge", typeHints: ["Totenkopf", "Kanonen", "Ozean", "Schatz"] },
    { word: "Tropfsteinhöhle", hint: "Jahrtausende alte Skulpturen aus Kalk", typeHints: ["tropft", "kalt", "dunkel", "Stalaktiten"] },
    { word: "Wolkenkratzer", hint: "sticht in die Wolken", typeHints: ["Glas", "Fahrstuhl", "Skyline", "hoch"] },
    { word: "Gewächshaus", hint: "Sommer erzwingen im Winter", typeHints: ["Glas", "Pflanzen", "warm", "Feuchtigkeit"] },
    { word: "Unterwasserhotel", hint: "schlafen mit Fischen vor dem Fenster", typeHints: ["Meer", "Glas", "Tauchen", "luxuriös"] },
  ],
  Tiere: [
    { word: "Elefant", hint: "größtes Landtier", typeHints: ["Rüssel", "Stoßzähne", "grau", "Gedächtnis"] },
    { word: "Delfin", hint: "klügstes Meerestier", typeHints: ["springt", "Echolot", "Ozean", "Flipper"] },
    { word: "Panda", hint: "schwarz-weißer Bambusfresser", typeHints: ["China", "selten", "süß", "Bambus"] },
    { word: "Pinguin", hint: "kann nicht fliegen aber schwimmt super", typeHints: ["Eis", "Frack", "watschelt", "Antarktis"] },
    { word: "Krokodil", hint: "lebt seit Dinosaurierzeiten", typeHints: ["Zähne", "Fluss", "lauert", "Schnappt"] },
    { word: "Adler", hint: "Symbol der Freiheit", typeHints: ["Schnabel", "Berge", "scharf", "Flügel"] },
    { word: "Gorilla", hint: "größter Affe", typeHints: ["stark", "Dschungel", "schlägt auf Brust", "schwarz"] },
    { word: "Gepard", hint: "schnellstes Landtier", typeHints: ["Flecken", "Sprint", "dünn", "Afrika"] },
    { word: "Oktopus", hint: "acht Arme, kein Knochen", typeHints: ["Tinte", "schlau", "Arme", "Meer"] },
    { word: "Fledermaus", hint: "fliegt in der Nacht mit Ultraschall", typeHints: ["Höhle", "blind", "Echolot", "Flügel"] },
    { word: "Qualle", hint: "durchsichtig und kann stechen", typeHints: ["Tentakel", "Meer", "gallertig", "leuchtet"] },
    { word: "Nashorn", hint: "Horn auf der Nase", typeHints: ["Horn", "gepanzert", "Afrika", "gefährdet"] },
    { word: "Flamingo", hint: "steht auf einem Bein", typeHints: ["pink", "ein Bein", "Wasser", "Schwarm"] },
    { word: "Axolotl", hint: "regeneriert verlorene Gliedmaßen", typeHints: ["Mexiko", "Kiemen", "seltsam", "lächelt"] },
    { word: "Komododrache", hint: "größte lebende Eidechse", typeHints: ["Indonesien", "giftig", "groß", "Echse"] },
    { word: "Wal", hint: "größtes Tier der Erde", typeHints: ["Ozean", "taucht", "singt", "riesig"] },
    { word: "Pfau", hint: "Rad schlagen zum Imponieren", typeHints: ["Federn", "bunt", "Rad", "stolz"] },
    { word: "Chamäleon", hint: "wechselt die Farbe", typeHints: ["Farbe", "langsam", "Zunge", "Äste"] },
    { word: "Hai", hint: "gefürchteter Jäger der Meere", typeHints: ["Zähne", "Flosse", "Ozean", "fürchterlich"] },
    { word: "Papagei", hint: "spricht nach", typeHints: ["bunt", "Schnabel", "spricht", "Tropenwald"] },
    { word: "Ameise", hint: "stärker als ihr Gewicht", typeHints: ["Kolonie", "trägt viel", "klein", "Hügel"] },
    { word: "Biene", hint: "macht Honig und bestäubt Blumen", typeHints: ["Stachel", "Honig", "Blüten", "Schwarm"] },
    { word: "Skorpion", hint: "giftige Peitsche am Schwanz", typeHints: ["Schwanz", "Wüste", "Stich", "gruselig"] },
    { word: "Eisbär", hint: "König der Arktis", typeHints: ["weiß", "Eis", "schwimmt", "Bär"] },
    { word: "Piranha", hint: "scharfe Zähne im Amazonas", typeHints: ["Zähne", "Fluss", "Schwarm", "gefährlich"] },
    { word: "Löwe", hint: "König der Savanne", typeHints: ["Mähne", "brüllt", "Rudel", "Afrika"] },
    { word: "Giraffe", hint: "langer Hals fürs Futter oben", typeHints: ["Flecken", "hoch", "Afrika", "Akazien"] },
    { word: "Koala", hint: "schläft 22 Stunden", typeHints: ["Eukalyptus", "Australien", "flauschig", "Baum"] },
    { word: "Känguru", hint: "Baby im Beutel", typeHints: ["Australien", "hüpft", "Beutel", "boxt"] },
    { word: "Otter", hint: "schläft auf dem Wasser haltend", typeHints: ["Händchen halten", "Fluss", "Fisch", "verspielt"] },
    { word: "Waschbär", hint: "wäscht sein Essen", typeHints: ["Maske", "Pfoten", "Mülltonne", "nachtaktiv"] },
    { word: "Lama", hint: "spuckt wenn es sauer ist", typeHints: ["Anden", "Wolle", "spuckt", "Lasten"] },
    { word: "Alpaka", hint: "süßere Version des Lamas", typeHints: ["flauschig", "Wolle", "Peru", "Tierpark"] },
    { word: "Biber", hint: "baut Dämme aus Holz", typeHints: ["Zähne", "Schwanz flach", "Fluss", "Holz"] },
    { word: "Nilpferd", hint: "aggressivstes Tier Afrikas", typeHints: ["Wasser", "Maul weit auf", "schwer", "grau"] },
    { word: "Schneeleopard", hint: "seltenste Großkatze", typeHints: ["Himalaya", "Flecken", "Bergkette", "selten"] },
    { word: "Kolibri", hint: "fliegt rückwärts", typeHints: ["winzig", "Blüten", "summt", "schnelle Flügel"] },
    { word: "Schildkröte", hint: "trägt ihr Haus", typeHints: ["Panzer", "langsam", "alt", "Meer oder Land"] },
    { word: "Seepferdchen", hint: "Männchen trägt die Babys aus", typeHints: ["Rüssel", "Meer", "klein", "aufrecht"] },
    { word: "Mantarochen", hint: "fliegt durchs Wasser", typeHints: ["Flügel", "flach", "Ozean", "groß"] },
    { word: "Orang-Utan", hint: "lebt allein im Regenwald", typeHints: ["orange", "Borneo", "klug", "Werkzeug"] },
    { word: "Erdmännchen", hint: "hält Wache für die Gruppe", typeHints: ["aufrecht", "Wüste", "Wachposten", "Clan"] },
  ],
  "Tiere (Exotisch)": [
    { word: "Axolotl", hint: "sieht aus wie ein Lächeln im Wasser", typeHints: ["Mexiko", "rosa", "Kiemen", "nachwächst"] },
    { word: "Aye-Aye", hint: "gruseligster Finger der Tierwelt", typeHints: ["Madagaskar", "Nacht", "langer Finger", "Auge groß"] },
    { word: "Blobfish", hint: "trauriges Gesicht aus der Tiefsee", typeHints: ["tief", "hässlich", "Meer", "gallertartig"] },
    { word: "Tardigrad", hint: "überlebt selbst im Weltall", typeHints: ["mikroskopisch", "Wasser", "unzerstörbar", "Moostierchen"] },
    { word: "Okapi", hint: "halb Zebra, halb Giraffe", typeHints: ["Streifen", "Regenwald", "selten", "Zunge lang"] },
    { word: "Platypus", hint: "legt Eier obwohl Säugetier", typeHints: ["Schnabel", "Australien", "Schwanz", "giftig"] },
    { word: "Mantis-Garnele", hint: "sieht mehr Farben als alle anderen", typeHints: ["Meer", "bunt", "Schlag", "Augen"] },
    { word: "Pistolengarnele", hint: "Schuss aus der Schere", typeHints: ["Knall", "Wasser", "Schere", "Schall"] },
    { word: "Fossa", hint: "Madagaskars Spitzenräuber", typeHints: ["Madagaskar", "Katze-ähnlich", "Klettern", "selten"] },
    { word: "Quokka", hint: "glücklichstes Tier der Welt", typeHints: ["Australien", "lächelt", "Selfie", "Insel"] },
    { word: "Nasenbär", hint: "langer Rüssel, buschiger Schwanz", typeHints: ["Südamerika", "Rüssel", "neugierig", "Gruppe"] },
    { word: "Binturong", hint: "riecht nach Popcorn", typeHints: ["Asien", "Popcorn-Geruch", "klettern", "buschig"] },
    { word: "Kakapo", hint: "Papagei der nicht fliegen kann", typeHints: ["Neuseeland", "grün", "flugunfähig", "selten"] },
    { word: "Tapir", hint: "lebt wie ein Mini-Nashorn", typeHints: ["Rüssel", "Südamerika", "Wald", "schwimmt"] },
    { word: "Gürteltier", hint: "rollt sich zur Kugel zusammen", typeHints: ["Panzer", "Südamerika", "rollt sich", "gräbt"] },
  ],
  Geschichte: [
    { word: "Pyramide", hint: "Grabmal der Pharaonen", typeHints: ["Ägypten", "Wüste", "alt", "riesig"] },
    { word: "Römisches Reich", hint: "herrschte über halb Europa", typeHints: ["Toga", "Gladiatoren", "Latein", "Kolosseum"] },
    { word: "Wikinger", hint: "segelten bis nach Amerika", typeHints: ["Langschiff", "Helm", "Skandinavien", "Nordmeer"] },
    { word: "Berliner Mauer", hint: "teilte eine Stadt in zwei", typeHints: ["Berlin", "DDR", "Fall", "Beton"] },
    { word: "Mondlandung", hint: "ein kleiner Schritt für einen Menschen", typeHints: ["1969", "Astronaut", "NASA", "Staubig"] },
    { word: "Französische Revolution", hint: "Freiheit, Gleichheit, Brüderlichkeit", typeHints: ["Paris", "Guillotine", "Volk", "Könige"] },
    { word: "Zweiter Weltkrieg", hint: "größter Konflikt der Geschichte", typeHints: ["Hitler", "Bombe", "Europa", "1945"] },
    { word: "Kleopatra", hint: "Königin des alten Ägypten", typeHints: ["Nil", "Schönheit", "Pharaonin", "Caesar"] },
    { word: "Kolosseum", hint: "Arena für Gladiatorenkämpfe", typeHints: ["Rom", "Bogen", "alt", "Kämpfe"] },
    { word: "Schießpulver", hint: "veränderte die Kriegsführung für immer", typeHints: ["Knall", "China", "Kanone", "Explosion"] },
    { word: "D-Day", hint: "Landung der Alliierten in der Normandie", typeHints: ["Strand", "1944", "Krieg", "Amerika"] },
    { word: "Mauerfall", hint: "1989 in Berlin", typeHints: ["Deutschland", "Freiheit", "DDR", "Jubel"] },
    { word: "Atombombe", hint: "zerstörte zwei japanische Städte", typeHints: ["Pilz", "Hiroshima", "Strahlung", "Krieg"] },
    { word: "Pest", hint: "tötete ein Drittel Europas", typeHints: ["Mittelalter", "Ratte", "Seuche", "schwarz"] },
    { word: "Kolumbus", hint: "entdeckte Amerika aus europäischer Sicht", typeHints: ["Schiff", "Spanien", "1492", "Irrtum"] },
    { word: "Spartakus", hint: "Sklave der gegen Rom rebellierte", typeHints: ["Sklave", "Aufstand", "Rom", "Niederlage"] },
    { word: "Napoleon", hint: "französischer Kaiser und Feldherr", typeHints: ["klein", "Hut", "Frankreich", "Russland"] },
    { word: "Konzentrationslager", hint: "Ort des Nazi-Verbrechens", typeHints: ["Stacheldraht", "Dunkel", "Holocaust", "Geschichte"] },
    { word: "Steinzeit", hint: "Werkzeuge aus Stein", typeHints: ["Höhle", "Feuer", "Keule", "alt"] },
    { word: "Kreuzzüge", hint: "religiöse Kriege im Mittelalter", typeHints: ["Ritter", "Jerusalem", "Kreuz", "Kirche"] },
  ],
  Wissenschaft: [
    { word: "Schwarzes Loch", hint: "nichts entkommt seiner Schwerkraft", typeHints: ["Weltraum", "verschlingt", "dunkel", "Gravitation"] },
    { word: "DNA", hint: "Bauplan des Lebens", typeHints: ["Doppelhelix", "Vererbung", "Zelle", "einzigartig"] },
    { word: "Schwerkraft", hint: "hält uns auf der Erde", typeHints: ["Apfel", "Newton", "Anziehung", "Kraft"] },
    { word: "Evolution", hint: "Arten verändern sich über Jahrmillionen", typeHints: ["Darwin", "Anpassung", "natürliche Selektion", "Fossilien"] },
    { word: "Antibiotika", hint: "kämpft gegen Bakterien", typeHints: ["Pille", "Arzt", "Bakterien", "Fleming"] },
    { word: "Periodensystem", hint: "alle Elemente im Überblick", typeHints: ["Chemie", "Symbole", "Tabelle", "Elemente"] },
    { word: "Fotosynthese", hint: "Pflanzen machen Zucker aus Licht", typeHints: ["Sonne", "Chlorophyll", "Sauerstoff", "grün"] },
    { word: "Relativitätstheorie", hint: "Einstein fand sie heraus", typeHints: ["Einstein", "Lichtgeschwindigkeit", "Raumzeit", "E=mc²"] },
    { word: "Klimawandel", hint: "die Erde wird wärmer", typeHints: ["CO2", "Gletscher", "Hitze", "Zukunft"] },
    { word: "Quantenphysik", hint: "Physik des sehr Kleinen", typeHints: ["Teilchen", "Welle", "seltsam", "Atom"] },
    { word: "Gentherapie", hint: "Krankheiten per DNA heilen", typeHints: ["Zukunft", "DNA", "Medizin", "Forschung"] },
    { word: "Mars", hint: "der rote Nachbarplanet", typeHints: ["rot", "Staubsturm", "Rover", "Besiedlung"] },
    { word: "Impfung", hint: "trainiert das Immunsystem", typeHints: ["Spritze", "Schutz", "Immunsystem", "Herde"] },
    { word: "Elektromagnet", hint: "Magnet durch Strom", typeHints: ["Spule", "Strom", "zieht an", "Junkyard"] },
    { word: "Plattentektonik", hint: "Kontinente bewegen sich", typeHints: ["Erdbeben", "Vulkan", "langsam", "Platten"] },
    { word: "Neuron", hint: "Nervenzelle im Gehirn", typeHints: ["Signal", "Gehirn", "Netz", "elektrisch"] },
    { word: "Laser", hint: "gebündeltes Lichtstrahlen", typeHints: ["Strahl", "präzise", "Licht", "Schneiden"] },
    { word: "Antimaterie", hint: "das Gegenteil von normaler Materie", typeHints: ["explodiert", "selten", "Forschung", "Symmetrie"] },
    { word: "Hibernation", hint: "Tiere schlafen den Winter durch", typeHints: ["Bär", "kalt", "langsam", "Fettreserven"] },
    { word: "Mikrowelle", hint: "erhitzt Wasser in Lebensmitteln", typeHints: ["Strahlung", "Küche", "schnell", "rotiert"] },
    { word: "Quantenverschränkung", hint: "zwei Teilchen verbunden über jede Distanz", typeHints: ["Physik", "sofort", "Einstein", "Teilchen"] },
    { word: "Schrödinger-Katze", hint: "tot und lebendig gleichzeitig", typeHints: ["Gedankenexperiment", "Quantenphysik", "Kiste", "Paradoxon"] },
    { word: "Biolumineszenz", hint: "Lebewesen leuchten selbst", typeHints: ["Tiefsee", "Glühwürmchen", "blau", "Chemie"] },
    { word: "CRISPR", hint: "Schere für die DNA", typeHints: ["Genbearbeitung", "Labor", "Zukunft", "Ethik"] },
    { word: "Dunkle Materie", hint: "alles ist davon umgeben, niemand sieht es", typeHints: ["unsichtbar", "Universum", "Gravitation", "Rätsel"] },
    { word: "Stringtheorie", hint: "alles ist ein winziger Faden", typeHints: ["Dimensionen", "Physik", "umstritten", "Mathematik"] },
    { word: "Fermi-Paradoxon", hint: "wo sind all die Aliens?", typeHints: ["Weltall", "Intelligenz", "Frage", "Enrico"] },
    { word: "Turing-Test", hint: "kann man Mensch von Maschine unterscheiden?", typeHints: ["KI", "Alan Turing", "Gespräch", "Test"] },
    { word: "Higgs-Boson", hint: "Teilchen das Masse gibt", typeHints: ["CERN", "Beschleuniger", "Gottes Teilchen", "2012"] },
    { word: "Butterfly-Effekt", hint: "kleines Flattern verändert alles", typeHints: ["Chaos", "Wetter", "Schmetterling", "Brasilien"] },
    { word: "Dunning-Kruger-Effekt", hint: "man denkt man weiß mehr als man weiß", typeHints: ["Psychologie", "Selbstüberschätzung", "Experten", "Unwissen"] },
    { word: "Mandela-Effekt", hint: "falsche kollektive Erinnerung", typeHints: ["Erinnerung", "falsch", "viele glauben es", "Internetphänomen"] },
    { word: "Placebo", hint: "wirkt obwohl es nichts enthält", typeHints: ["Pille", "Psyche", "Studie", "Glaube"] },
    { word: "Osmose", hint: "Wasser wandert durch Wände", typeHints: ["Membran", "Konzentration", "Biologie", "Wasser"] },
    { word: "Entropie", hint: "alles wird mit der Zeit chaotischer", typeHints: ["Unordnung", "Zeit", "Energie", "Physik"] },
    { word: "Neutrino", hint: "fliegt durch alles hindurch", typeHints: ["Teilchen", "unsichtbar", "Weltall", "kaum wechselwirkt"] },
    { word: "Gravitationswelle", hint: "Schallwelle durch die Raumzeit", typeHints: ["Einstein", "Kollision", "LIGO", "Welle"] },
  ],
  "Fantasie & Mythos": [
    { word: "Drache", hint: "feuerspeiend und geflügelt", typeHints: ["Schuppen", "Schatz", "mittelalterlich", "Feuer"] },
    { word: "Einhorn", hint: "Pferd mit Horn", typeHints: ["Horn", "magisch", "Regenbogen", "Märchen"] },
    { word: "Vampire", hint: "saugen Blut in der Nacht", typeHints: ["Knoblauch", "Sarg", "Unsterblich", "Cape"] },
    { word: "Meerjungfrau", hint: "halb Frau, halb Fisch", typeHints: ["Meer", "Flosse", "singt", "Riff"] },
    { word: "Werwolf", hint: "verwandelt sich bei Vollmond", typeHints: ["Vollmond", "Fell", "Heult", "Silber"] },
    { word: "Troll", hint: "lebt unter Brücken", typeHints: ["Brücke", "grob", "groß", "Märchen"] },
    { word: "Fee", hint: "klein mit Flügeln und Zauberstab", typeHints: ["Flügel", "glitzert", "Wunsch", "klein"] },
    { word: "Zombie", hint: "Toter der weiterläuft", typeHints: ["Apokalypse", "Hirn", "langsam", "Biss"] },
    { word: "Minotaurus", hint: "Stierkopf, Menschenkörper", typeHints: ["Labyrinth", "Griechenland", "Stier", "Theseus"] },
    { word: "Phönix", hint: "Vogel der aus der Asche aufersteht", typeHints: ["Flammen", "Wiedergeburt", "Vogel", "unsterblich"] },
    { word: "Riese", hint: "riesiger Mensch", typeHints: ["groß", "stark", "Burg", "Fee"] },
    { word: "Elf", hint: "spitzohrige Waldwesen", typeHints: ["Wald", "Spitzohren", "Bogenschütze", "Tolkien"] },
    { word: "Gnom", hint: "kleines Wesen im Garten", typeHints: ["klein", "Garten", "Hut", "Schatz"] },
    { word: "Sirene", hint: "lockt Seeleute mit Gesang ins Verderben", typeHints: ["Gesang", "Meer", "verführt", "Schiff"] },
    { word: "Medusa", hint: "ihr Blick versteinert", typeHints: ["Schlangen", "Haare", "versteinert", "Griechenland"] },
    { word: "Gorgon", hint: "mythisches schuppiges Monster", typeHints: ["Schuppen", "Blick", "Mythos", "Stein"] },
    { word: "Banshee", hint: "irischer Geist der den Tod ankündigt", typeHints: ["Schrei", "irland", "Geist", "weiblich"] },
    { word: "Golem", hint: "aus Lehm gemachter Diener", typeHints: ["Lehm", "jüdisch", "Schutz", "Wort auf Stirn"] },
    { word: "Leprechaun", hint: "irischer Kobold mit Goldtopf", typeHints: ["Irland", "Gold", "grün", "Regenbogen"] },
    { word: "Yeti", hint: "Schneemonster im Himalaya", typeHints: ["Schnee", "Berge", "weiß", "geheimnisvoll"] },
  ],
  Technologie: [
    { word: "Künstliche Intelligenz", hint: "lernt wie ein Mensch", typeHints: ["Daten", "Modell", "Zukunft", "Computer"] },
    { word: "Bitcoin", hint: "digitales Geld ohne Bank", typeHints: ["Blockchain", "Mining", "anonym", "Wert schwankt"] },
    { word: "Virtual Reality", hint: "Brille in andere Welten", typeHints: ["Brille", "Simulation", "Spiele", "immersiv"] },
    { word: "Drohne", hint: "fliegt ohne Piloten", typeHints: ["Propeller", "Kamera", "ferngesteuert", "Paket"] },
    { word: "Elektroauto", hint: "tankt Strom statt Benzin", typeHints: ["Akku", "lautlos", "Tesla", "laden"] },
    { word: "Solaranlage", hint: "Sonne wird zu Strom", typeHints: ["Dach", "Panels", "grün", "Energie"] },
    { word: "Quantencomputer", hint: "rechnet mit Quantenphysik", typeHints: ["schnell", "Forschung", "Qubits", "Zukunft"] },
    { word: "Satellit", hint: "kreist um die Erde", typeHints: ["Orbit", "Signal", "Navigation", "Weltraum"] },
    { word: "3D-Drucker", hint: "druckt echte Objekte", typeHints: ["Schicht", "Plastik", "Modell", "Bauteile"] },
    { word: "Algorithmus", hint: "Schritt-für-Schritt-Anleitung für Computer", typeHints: ["Logik", "Code", "Schritte", "Entscheidung"] },
    { word: "Firewall", hint: "schützt Netzwerke vor Angreifern", typeHints: ["Sicherheit", "blockt", "digital", "Schutzwall"] },
    { word: "Streaming", hint: "Filme ohne Download", typeHints: ["Internet", "sofort", "Abo", "Puffer"] },
    { word: "Cloud", hint: "Datenspeicher im Internet", typeHints: ["online", "Speicher", "überall", "Server"] },
    { word: "GPS", hint: "findet deinen Weg", typeHints: ["Satellit", "Navigation", "Auto", "Position"] },
    { word: "Chatbot", hint: "antwortet wie ein Mensch", typeHints: ["Text", "automatisch", "KI", "Service"] },
    { word: "Touchscreen", hint: "bedient mit Fingern", typeHints: ["Glas", "tippen", "Handy", "Geste"] },
    { word: "Bluetooth", hint: "verbindet Geräte kabellos", typeHints: ["kurze Distanz", "Kopfhörer", "Lautsprecher", "Pairing"] },
    { word: "App Store", hint: "Marktplatz für Anwendungen", typeHints: ["Apple", "herunterladen", "Bewertung", "Icon"] },
    { word: "Passwort", hint: "geheim und oft vergessen", typeHints: ["Zeichen", "sicher", "Login", "Schutz"] },
    { word: "Roboter", hint: "Maschine die Aufgaben erledigt", typeHints: ["Metall", "programmiert", "Fabrik", "Zukunft"] },
    { word: "Hackerangriff", hint: "Einbruch ins digitale System", typeHints: ["Daten", "geheim", "Schaden", "Code"] },
    { word: "Augmented Reality", hint: "digitale Schicht über der echten Welt", typeHints: ["Brille", "Pokémon Go", "überlagert", "Kamera"] },
    { word: "Serverraum", hint: "kalt und voller blinkender Lichter", typeHints: ["kalt", "Kabel", "Internet", "Rechner"] },
    { word: "USB-Stick", hint: "kleiner Datenspeicher", typeHints: ["Stecken", "Daten", "klein", "verloren"] },
    { word: "Deepfake", hint: "gefälschtes Video mit echtem Gesicht", typeHints: ["täuscht", "KI", "Video", "Gesicht"] },
    { word: "Hologramm", hint: "3D-Bild aus Licht", typeHints: ["Projektion", "Sci-Fi", "blau", "greifbar nicht"] },
    { word: "Zeitmaschine", hint: "in Filmen immer kaputt", typeHints: ["Zukunft", "Vergangenheit", "Hebel", "Paradoxon"] },
    { word: "Exoskelett", hint: "Anzug der Kräfte verleiht", typeHints: ["Metall", "Muskeln", "Militär", "Gehilfe"] },
    { word: "Jetpack", hint: "Rückenmotor zum Fliegen", typeHints: ["Rücken", "Düsen", "Traum", "Zukunft"] },
    { word: "Smartwatch", hint: "Computer am Handgelenk", typeHints: ["Puls", "Benachrichtigung", "klein", "Armband"] },
    { word: "Biochip", hint: "Technik unter der Haut", typeHints: ["implantiert", "Daten", "Sensor", "Zukunft"] },
    { word: "Hyperloop", hint: "Reisen in der Röhre", typeHints: ["Vakuum", "schnell", "Elon Musk", "Kapsel"] },
    { word: "Sprachassistent", hint: "hört immer zu", typeHints: ["Hey Siri", "Lautsprecher", "smart", "Wohnzimmer"] },
    { word: "Selbstfahrendes Auto", hint: "fährt ohne Hände am Steuer", typeHints: ["Sensoren", "Kamera", "KI", "Zukunft"] },
    { word: "Fusionsreaktor", hint: "Energie wie die Sonne", typeHints: ["Plasma", "Hitze", "Forschung", "Zukunft"] },
    { word: "Nanoroboter", hint: "winzige Maschinen im Körper", typeHints: ["Blut", "Medizin", "mikroskopisch", "Heilung"] },
    { word: "Gehirnschnittstelle", hint: "Computer direkt im Kopf", typeHints: ["Neuralink", "Elektroden", "Gedanken", "Zukunft"] },
    { word: "Quantenteleportation", hint: "Information sofort überall", typeHints: ["Physik", "Teilchen", "kein Reisen", "Labor"] },
    { word: "Terraforming", hint: "einen Planeten bewohnbar machen", typeHints: ["Mars", "Atmosphäre", "Jahrtausende", "Sci-Fi"] },
  ],
  Videospiele: [
    { word: "Fortnite", hint: "Bau und schieß ums Überleben", typeHints: ["Battle Royale", "Bauen", "Insel", "Tanz"] },
    { word: "GTA", hint: "Kriminelle in einer offenen Stadt", typeHints: ["Auto klauen", "Polizei", "Stadt", "offen"] },
    { word: "League of Legends", hint: "5 gegen 5 auf einer Karte", typeHints: ["Lane", "Turm", "Champions", "Team"] },
    { word: "Elden Ring", hint: "sehr schwieriges Fantasy-RPG", typeHints: ["Boss", "Tod", "offen", "Schwert"] },
    { word: "Among Us", hint: "finde den Verräter an Bord", typeHints: ["Raumschiff", "Aufgaben", "Verrat", "Crew"] },
    { word: "FIFA", hint: "virtueller Fußball", typeHints: ["Karten", "Turnier", "Tor", "Jahresausgabe"] },
    { word: "Zelda", hint: "Link rettet immer wieder Hyrule", typeHints: ["Schwert", "Dungeons", "Prinzessin", "Nintendo"] },
    { word: "Counter-Strike", hint: "Terroristen gegen Anti-Terror", typeHints: ["Bombe", "Headshot", "Team", "PC"] },
    { word: "Tetris", hint: "Blöcke stapeln und Reihen löschen", typeHints: ["Blöcke", "fällt", "Reihe", "schneller"] },
    { word: "Pac-Man", hint: "gelbe Kugel frisst Punkte", typeHints: ["Geister", "Labyrinth", "gelb", "Punkte"] },
    { word: "Roblox", hint: "Spieler bauen eigene Spiele", typeHints: ["Blöcke", "Kids", "Erstellen", "Avatare"] },
    { word: "Valorant", hint: "taktischer Shooter mit Fähigkeiten", typeHints: ["Agenten", "Schießen", "Team", "Fähigkeiten"] },
    { word: "Dark Souls", hint: "stirb und lerne", typeHints: ["Bosse", "schwer", "Mittelalter", "Bonfire"] },
    { word: "Stardew Valley", hint: "Farm und Freundschaften", typeHints: ["Ernten", "ruhig", "Pixel", "Dorf"] },
    { word: "Cyberpunk 2077", hint: "Neon-Stadt der Zukunft", typeHints: ["Neon", "Hacking", "Implantate", "Zukunft"] },
  ],
  Städte: [
    { word: "Paris", hint: "Stadt der Liebe", typeHints: ["Eiffelturm", "Mode", "Frankreich", "Baguette"] },
    { word: "Tokio", hint: "megagroße japanische Metropole", typeHints: ["dicht", "Neon", "Sushi", "Zug"] },
    { word: "New York", hint: "die Stadt die niemals schläft", typeHints: ["Wolkenkratzer", "Taxi", "Broadway", "Pizza"] },
    { word: "Berlin", hint: "Hauptstadt mit Geschichte", typeHints: ["Mauer", "Techno", "Brandenburger Tor", "Döner"] },
    { word: "Dubai", hint: "Wolkenkratzer in der Wüste", typeHints: ["Luxus", "heiß", "Wüste", "Burj Khalifa"] },
    { word: "Rom", hint: "ewige Stadt mit Kolosseum", typeHints: ["Kolosseum", "Pasta", "antik", "Vatikan"] },
    { word: "Rio de Janeiro", hint: "Karneval und Copacabana", typeHints: ["Karneval", "Strand", "Christ-Statue", "Brasilien"] },
    { word: "Las Vegas", hint: "Stadt der Sünde", typeHints: ["Kasino", "Wüste", "Neon", "Heiraten"] },
    { word: "London", hint: "Big Ben und Regen", typeHints: ["Regen", "Doppeldecker", "Queen", "Themse"] },
    { word: "Sydney", hint: "Opernhaus am Wasser", typeHints: ["Opernhaus", "Australien", "Strand", "Brücke"] },
    { word: "Moskau", hint: "Roter Platz und Kreml", typeHints: ["Russland", "Kreml", "kalt", "Matrjoschka"] },
    { word: "Mumbai", hint: "Bollywood-Hauptstadt", typeHints: ["Indien", "Bollywood", "dicht", "Gewürze"] },
    { word: "Singapur", hint: "kleines Land mit riesigem Hafen", typeHints: ["sauber", "Asien", "Hafen", "modern"] },
    { word: "Amsterdam", hint: "Grachten und Fahrräder", typeHints: ["Kanal", "Fahrrad", "Tulpen", "Niederlande"] },
    { word: "Istanbul", hint: "Stadt auf zwei Kontinenten", typeHints: ["Bosporus", "Moschee", "Türkei", "Brücke"] },
    { word: "Buenos Aires", hint: "Paris Südamerikas", typeHints: ["Tango", "Argentinien", "europäisch", "Steaks"] },
    { word: "Wien", hint: "Mozarts Heimat", typeHints: ["Klassik", "Kaffeehaus", "Österreich", "Walzer"] },
    { word: "Kapstadt", hint: "am Kap der guten Hoffnung", typeHints: ["Tafelberg", "Südafrika", "Wein", "Meer"] },
    { word: "Barcelona", hint: "Gaudís bunte Architektur", typeHints: ["Sagrada Família", "Tapas", "Spanien", "Strand"] },
    { word: "Kyoto", hint: "alte japanische Kaiserstadt", typeHints: ["Tempel", "Kirschblüten", "Japan", "traditionell"] },
  ],
  "Mode & Stil": [
    { word: "Sneaker", hint: "Sportschuhe als Statussymbol", typeHints: ["Nike", "Sammler", "Sohle", "hype"] },
    { word: "Hoodie", hint: "bequemer Kapuzenpullover", typeHints: ["Kapuze", "warm", "lässig", "Taschen"] },
    { word: "Jeans", hint: "aus blauem Denim", typeHints: ["blau", "Denim", "Nieten", "zeitlos"] },
    { word: "Louis Vuitton", hint: "Luxusmarke mit Monogramm", typeHints: ["Tasche", "Luxus", "Muster", "Frankreich"] },
    { word: "Trenchcoat", hint: "langer Mantel mit Gürtel", typeHints: ["lang", "Detektiv", "Regen", "Gürtel"] },
    { word: "Sonnenbrille", hint: "schützt vor Sonne und ist stylisch", typeHints: ["UV", "Sommer", "cool", "Gläser"] },
    { word: "Lippenstift", hint: "Farbe für die Lippen", typeHints: ["rot", "Tube", "Kuss", "Make-up"] },
    { word: "Sakko", hint: "formelles Jackett", typeHints: ["Knöpfe", "Business", "Revers", "elegant"] },
    { word: "Vintage", hint: "alt aber wiederentdeckt", typeHints: ["retro", "alt", "Stil", "Flohmarkt"] },
    { word: "Streetwear", hint: "urbaner Kleidungsstil", typeHints: ["Straße", "lässig", "Brand", "Jugend"] },
    { word: "Parfüm", hint: "unsichtbarer Eindruck", typeHints: ["Duft", "Flakon", "Spray", "teuer"] },
    { word: "Trachtenhut", hint: "bayrischer Hut mit Feder", typeHints: ["Bayern", "Oktoberfest", "Feder", "grün"] },
    { word: "High Heels", hint: "hohe Absätze", typeHints: ["Absatz", "elegant", "hoch", "Schmerzen"] },
    { word: "Manschettenknöpfe", hint: "kleines Detail großer Wirkung", typeHints: ["Hemd", "elegant", "Metall", "Geschäft"] },
    { word: "Parka", hint: "langer warmer Wintermantel", typeHints: ["Kapuze", "Fell", "Winter", "lang"] },
  ],
  Emotionen: [
    { word: "Heimweh", hint: "Sehnsucht nach zu Hause", typeHints: ["fern", "vermissen", "Erinnerung", "Familie"] },
    { word: "Eifersucht", hint: "wenn jemand anderes das bekommt was man will", typeHints: ["neidisch", "Liebe", "Misstrauen", "grün"] },
    { word: "Euphorie", hint: "überwältigende Freude", typeHints: ["hoch", "Jubel", "Energie", "ausgelassen"] },
    { word: "Melancholie", hint: "stille tiefe Traurigkeit", typeHints: ["grau", "nachdenklich", "Herbst", "leise"] },
    { word: "Scham", hint: "man möchte im Boden versinken", typeHints: ["rot werden", "peinlich", "Blick senken", "still"] },
    { word: "Ehrgeiz", hint: "brennender Wille zu gewinnen", typeHints: ["Ziel", "arbeiten", "gewinnen", "fokussiert"] },
    { word: "Dankbarkeit", hint: "Wertschätzung für das was man hat", typeHints: ["Lächeln", "warm", "Geste", "inne halten"] },
    { word: "Einsamkeit", hint: "allein und unverstanden", typeHints: ["still", "leer", "niemand", "Nacht"] },
    { word: "Angst", hint: "lähmt und schützt zugleich", typeHints: ["Herzklopfen", "Zittern", "dunkel", "Bedrohung"] },
    { word: "Schadenfreude", hint: "deutsches Wort das die Welt kennt", typeHints: ["lachen", "Pech anderer", "gemein", "heimlich"] },
    { word: "Fernweh", hint: "zieht einen in die Weite", typeHints: ["Reisen", "unbekannt", "Koffer", "Horizont"] },
    { word: "Weltschmerz", hint: "der Schmerz über den Zustand der Welt", typeHints: ["Nachrichten", "schwer", "melancholisch", "philosophisch"] },
    { word: "Lampenfieber", hint: "Angst vor dem großen Auftritt", typeHints: ["Bühne", "Herzklopfen", "Schweiß", "Publikum"] },
    { word: "Neid", hint: "will was der andere hat", typeHints: ["grün", "vergleichen", "still", "ungerecht"] },
    { word: "Nostalgie", hint: "süße Trauer über die Vergangenheit", typeHints: ["Erinnerung", "Kindheit", "damals", "warm"] },
    { word: "Empathie", hint: "fühlt was andere fühlen", typeHints: ["Mitgefühl", "verstehen", "zuhören", "verbinden"] },
    { word: "Stolz", hint: "Freude über eigene Leistung", typeHints: ["aufrecht", "Brust raus", "Erfolg", "Eltern"] },
    { word: "Neugier", hint: "will immer mehr wissen", typeHints: ["Fragen", "erkunden", "Kind", "offen"] },
    { word: "Enttäuschung", hint: "wenn Erwartungen nicht erfüllt werden", typeHints: ["hängende Schultern", "still", "gebrochen", "erwartet"] },
    { word: "Überraschung", hint: "man hat es nicht kommen sehen", typeHints: ["Augen auf", "unvorbereitet", "Schock", "Freude"] },
    { word: "Vertrauen", hint: "Grundlage jeder Beziehung", typeHints: ["offen", "ehrlich", "blind", "Stütze"] },
    { word: "Wut", hint: "heiß und laut", typeHints: ["rot", "Fäuste", "Schreien", "Kontrolle"] },
  ],
  Alltag: [
    { word: "Stau", hint: "Alptraum auf der Autobahn", typeHints: ["Autos", "warten", "Frust", "Bremsen"] },
    { word: "Wecker", hint: "holt einen morgens raus", typeHints: ["Klingeln", "Bett", "früh", "Snooze"] },
    { word: "Einkaufsliste", hint: "damit man nichts vergisst", typeHints: ["Papier", "Stift", "Supermarkt", "Haken"] },
    { word: "Waschmaschine", hint: "dreht sich im Kreis", typeHints: ["Trommel", "nass", "Pulver", "Schleudern"] },
    { word: "Müll", hint: "kommt einmal die Woche", typeHints: ["Tonne", "Geruch", "trennen", "Tüte"] },
    { word: "Parkplatz", hint: "manchmal ewig suchen", typeHints: ["Parken", "begrenzt", "Straße", "Münze"] },
    { word: "Wartezimmer", hint: "Zeit zum Nachdenken erzwungen", typeHints: ["Zeitschrift", "Stühle", "Arzt", "warten"] },
    { word: "Handtuch", hint: "nach dem Duschen unverzichtbar", typeHints: ["Frottee", "nass", "Bad", "wischen"] },
    { word: "Schlaf", hint: "zu wenig davon ist fatal", typeHints: ["Bett", "Träume", "Dunkel", "ruhig"] },
    { word: "Stress", hint: "modernes Dauerproblem", typeHints: ["Kopfweh", "Deadlines", "Hektik", "Erschöpfung"] },
    { word: "Urlaub", hint: "am liebsten immer", typeHints: ["Koffer", "Sonne", "frei", "fern"] },
    { word: "Montag", hint: "der unbeliebteste Tag", typeHints: ["Müde", "Woche", "Arbeit", "grau"] },
    { word: "Selfie", hint: "Foto von sich selbst", typeHints: ["Kamera", "vorne", "Instagram", "Pose"] },
    { word: "Warteschlange", hint: "Geduld auf die Probe gestellt", typeHints: ["lang", "warten", "Kasse", "Schlange"] },
    { word: "Hausaufgaben", hint: "nach der Schule noch mehr Schule", typeHints: ["Heft", "Tisch", "Pflicht", "lästig"] },
    { word: "Versicherung", hint: "zahlt wenn etwas schiefläuft", typeHints: ["Vertrag", "Prämie", "Schutz", "Formulare"] },
    { word: "Impftermin", hint: "kurzer Schmerz langer Schutz", typeHints: ["Arzt", "Nadel", "Pflaster", "Schutz"] },
    { word: "Geburtstag", hint: "jedes Jahr einmal", typeHints: ["Kerzen", "Torte", "Wünsche", "Geschenke"] },
    { word: "Detox", hint: "bewusst auf etwas verzichten", typeHints: ["Pause", "gesund", "Handy", "Diät"] },
    { word: "Sonntag", hint: "der Tag der Ruhe", typeHints: ["ruhig", "Frühstück", "Zeitung", "entspannt"] },
  ],
  Sonstiges: [
    { word: "Zirkus", hint: "Zelt voller Wunder und Artisten", typeHints: ["Manege", "Clown", "Trapez", "Tiere"] },
    { word: "Lügendetektor", hint: "misst Nervosität beim Lügen", typeHints: ["Maschine", "Polizei", "Antwort", "Herzschlag"] },
    { word: "Schwarzmarkt", hint: "illegaler Handel", typeHints: ["verboten", "geheim", "Ware", "Risiko"] },
    { word: "Gerücht", hint: "niemand weiß ob es stimmt", typeHints: ["Flüstern", "Schule", "weitererzählen", "Unsicher"] },
    { word: "Tagebuch", hint: "private Gedanken auf Papier", typeHints: ["Schloss", "geheim", "Stift", "Datum"] },
    { word: "Ritual", hint: "regelmäßige bedeutungsvolle Handlung", typeHints: ["Tradition", "Wiederholung", "bedeutungsvoll", "Gemeinschaft"] },
    { word: "Propaganda", hint: "gezielte Manipulation der Meinung", typeHints: ["Plakate", "Regierung", "einseitig", "Lüge"] },
    { word: "Selbstgespräch", hint: "laut denken", typeHints: ["allein", "Spiegel", "Gedanken", "komisch"] },
    { word: "Spionage", hint: "Geheimnisse stehlen", typeHints: ["geheim", "Mikrofon", "Schatten", "Agent"] },
    { word: "Erpressung", hint: "Geld durch Drohung", typeHints: ["Brief", "drohen", "Schweigen", "Macht"] },
    { word: "Undercover", hint: "verdeckt ermitteln", typeHints: ["Tarnung", "geheim", "Polizei", "Rolle"] },
    { word: "Sabotage", hint: "absichtlich etwas zerstören", typeHints: ["Absicht", "verbergen", "Schaden", "innen"] },
    { word: "Paranoia", hint: "man glaubt alle sind gegen einen", typeHints: ["Misstrauen", "allein", "Gedanken", "angespannt"] },
    { word: "Identitätsdiebstahl", hint: "jemand gibt sich als du aus", typeHints: ["Daten", "Internet", "kriminell", "Schaden"] },
    { word: "Flucht", hint: "raus aus einer gefährlichen Situation", typeHints: ["rennen", "Nacht", "schnell", "Angst"] },
    { word: "Amnestie", hint: "staatliche Begnadigung", typeHints: ["Gnade", "Staat", "Freiheit", "Gesetz"] },
    { word: "Verhör", hint: "intensives Befragen", typeHints: ["Lampe", "Raum", "Fragen", "Druck"] },
    { word: "Alibi", hint: "Beweis der Unschuld", typeHints: ["Zeuge", "Zeit", "Polizei", "Ort"] },
    { word: "Doppelagent", hint: "dient zwei Herren", typeHints: ["geheim", "Verrat", "Spion", "Loyalität"] },
    { word: "Tarnung", hint: "im Verborgenen bleiben", typeHints: ["Camouflage", "unsichtbar", "Natur", "Tier"] },
    { word: "Verdächtiger", hint: "könnte die Tat begangen haben", typeHints: ["Polizei", "Fragen", "Motiv", "Beweise"] },
    { word: "Whistleblower", hint: "deckt Missstände auf", typeHints: ["Mut", "Geheimnis", "enthüllen", "Schutz"] },
    { word: "Maskerade", hint: "verkleidet und unerkannt", typeHints: ["Maske", "Ball", "verkleidet", "geheimnisvoll"] },
    { word: "Detektivroman", hint: "wer hat es getan?", typeHints: ["Mord", "Rätsel", "Sherlock", "Spannung"] },
    { word: "Fluchtplan", hint: "genaue Strategie zum Entkommen", typeHints: ["Karte", "Timing", "Vorbereitung", "geheim"] },
    { word: "Verdacht", hint: "ein ungutes Gefühl", typeHints: ["Misstrauen", "Blick", "leise", "Hinweis"] },
    { word: "Täter", hint: "hat die Tat begangen", typeHints: ["schuldig", "Motiv", "Gericht", "Beweis"] },
    { word: "Zeuge", hint: "hat alles gesehen", typeHints: ["Aussage", "Gericht", "Blick", "wichtig"] },
    { word: "Tresor", hint: "sicherer Behälter für Wertvolles", typeHints: ["Kombination", "Stahl", "Bank", "geheim"] },
    { word: "Doppelleben", hint: "zwei Identitäten gleichzeitig", typeHints: ["geheim", "lügen", "erschöpfend", "riskant"] },
    { word: "Nachtclub", hint: "Tanzen bis zum Morgengrauen", typeHints: ["Licht", "Bass", "Einlass", "Nacht"] },
    { word: "Bande", hint: "Gruppe mit gemeinsamen Zielen", typeHints: ["Zusammenhalt", "Regeln", "Straße", "stark"] },
    { word: "Entführung", hint: "gegen den Willen festgehalten", typeHints: ["Lösegeld", "geheim", "Angst", "suchen"] },
    { word: "Ausweg", hint: "Lösung in einer ausweglosen Situation", typeHints: ["Hoffnung", "Türe", "letzter", "finden"] },
    { word: "Bluff", hint: "überzeugend lügen", typeHints: ["Poker", "riskant", "Gesicht", "täuschen"] },
    { word: "Komplize", hint: "Mitschuldiger", typeHints: ["zusammen", "schuldig", "Teamwork", "Verbrechen"] },
    { word: "Kronzeuge", hint: "wichtigster Zeuge der Anklage", typeHints: ["Schutz", "aussagen", "Gericht", "Schlüssel"] },
    { word: "Magie", hint: "alles scheint möglich", typeHints: ["Zauberstab", "Tricks", "Illusion", "staunen"] },
    { word: "Graffiti", hint: "Kunst oder Vandalismus?", typeHints: ["Wand", "Sprühdose", "bunt", "Straße"] },
    { word: "Tattoo", hint: "permanent auf der Haut", typeHints: ["Nadel", "Tinte", "schmerzt", "dauerhaft"] },
    { word: "Albtraum", hint: "schlechter Traum", typeHints: ["Nacht", "Angst", "schweißgebadet", "Dunkel"] },
    { word: "Déjà-vu", hint: "das Gefühl das schon erlebt zu haben", typeHints: ["Erinnerung", "seltsam", "Moment", "Wiederholung"] },
    { word: "Amnesie", hint: "Gedächtnisverlust", typeHints: ["vergessen", "Unfall", "Identität", "Verwirrung"] },
    { word: "Karma", hint: "was du gibst, kommt zurück", typeHints: ["Schicksal", "Gutes tun", "Hinduismus", "Kreislauf"] },
    { word: "Meditation", hint: "innere Ruhe finden", typeHints: ["Stille", "atmen", "Matte", "Fokus"] },
    { word: "Lotterie", hint: "Glück im Zahlenmeer", typeHints: ["Ticket", "Ziehung", "Millionen", "Zufall"] },
    { word: "Verschwörungstheorie", hint: "andere Erklärung für alles", typeHints: ["Zweifel", "Geheimnis", "YouTube", "Fakten ignorieren"] },
    { word: "Zeitkapsel", hint: "Botschaft für die Zukunft", typeHints: ["vergraben", "Brief", "Nostalgie", "öffnen in 50 Jahren"] },
    { word: "Streik", hint: "Arbeit kollektiv verweigern", typeHints: ["Plakate", "Gewerkschaft", "Lohn", "Protest"] },
    { word: "Cliffhanger", hint: "Serienende das einen nicht loslässt", typeHints: ["Serie", "warten", "Spannung", "offen"] },
    { word: "Ironie", hint: "man meint das Gegenteil", typeHints: ["Witz", "Ton", "Bedeutung", "clever"] },
    { word: "Bucketlist", hint: "Dinge die man vor dem Tod tun will", typeHints: ["Wünsche", "Ziele", "Liste", "Leben"] },
    { word: "Anonymität", hint: "niemand weiß wer du bist", typeHints: ["geheim", "Internet", "Maske", "unerkannt"] },
    { word: "Geheimnis", hint: "darf niemand wissen", typeHints: ["flüstern", "verborgen", "Vertrauen", "still"] },
  ],
  Anime: [
    { word: "A Silent Voice", hint: "Mädchen mit Hörbehinderung und ein Junge der Schulden begleicht", typeHints: ["Shoya", "Shoko", "X-Formen", "Schmetterling"] },
    { word: "Assassination Classroom", hint: "Alien-Lehrer der die Erde zerstören könnte", typeHints: ["Koro-sensei", "Gelb", "Mord", "Schulklasse"] },
    { word: "Attack on Titan", hint: "Riesen bedrohen die Menschheit hinter Mauern", typeHints: ["Mauern", "Titanen", "Soldaten", "Dreidimensionale Manöver"] },
    { word: "Berserk", hint: "Schwertkämpfer mit einem riesigen Schwert im dunklen Fantasy-Mittelalter", typeHints: ["Guts", "Griffith", "Dämonen", "Eisen"] },
    { word: "Black Clover", hint: "Waisenjunge ohne Magie will Zauberkönig werden", typeHints: ["Asta", "Yuno", "Schwert", "Grimoire"] },
    { word: "Bleach", hint: "Shinigami bekämpfen böse Geister mit einem riesigen Schwert", typeHints: ["Bankai", "Hohl", "Ichigo", "Roben"] },
    { word: "Blue Lock", hint: "Fußballprojekt sucht den besten Stürmer Japans", typeHints: ["Ego", "Fußball", "Tor", "Egoismus"] },
    { word: "Chainsaw Man", hint: "Teufelsjäger mit einer Kettensäge als Kopf", typeHints: ["Denji", "Pochita", "Teufel", "Blut"] },
    { word: "Code Geass", hint: "Rebell mit einem übernatürlichen Auge", typeHints: ["Geass", "Zero", "Mecha", "Rebellion"] },
    { word: "Death Note", hint: "Notizbuch das tötet wenn man einen Namen hineinschreibt", typeHints: ["L", "Shinigami", "Äpfel", "Gerechtigkeit"] },
    { word: "Demon Slayer", hint: "Bruder rettet seine Schwester von einem Dämonenfluch", typeHints: ["Schwert", "Atemtechniken", "Dämonen", "Nezuko"] },
    { word: "Detective Conan", hint: "Genie-Detektiv in einem Kinderkörper löst Fälle", typeHints: ["Conan", "Brille", "Mord", "Apotoxin"] },
    { word: "Dr. Stone", hint: "Wissenschaftler baut die Zivilisation nach einer Steinverwandlung wieder auf", typeHints: ["Senku", "Wissenschaft", "Stein", "Cola"] },
    { word: "Dragon Ball", hint: "Kämpfer sucht nach den magischen Kugeln", typeHints: ["Son Goku", "Kamehameha", "Dragon Balls", "Schwanz"] },
    { word: "Dragon Ball Z", hint: "Kämpfer trainieren für immer stärkere Gegner", typeHints: ["Saiyajin", "Super Saiyajin", "Cell", "Buu"] },
    { word: "Erased", hint: "Mann reist in die Vergangenheit um ein Verbrechen zu verhindern", typeHints: ["Satoru", "Mord", "Kalterfall", "Zeitreise"] },
    { word: "Fairy Tail", hint: "Magier-Gilde in einer Fantasiewelt", typeHints: ["Natsu", "Lucy", "Gilde", "Magie"] },
    { word: "Fate/stay night", hint: "Magier und antike Helden kämpfen um den Heiligen Gral", typeHints: ["Saber", "Gral", "Servant", "Befehlszauber"] },
    { word: "Fire Force", hint: "Feuerwehr bekämpft seltsame Flammen die Menschen verbrennen", typeHints: ["Shinra", "Feuer", "Dämon", "Adolla"] },
    { word: "Food Wars!", hint: "Kochduelle an einer Elite-Schule", typeHints: ["Soma", "Yukihira", "Essen", "Schürze"] },
    { word: "Frieren: Beyond Journey's End", hint: "Elfe kehrt zurück und begreift die Vergänglichkeit", typeHints: ["Frieren", "Elfe", "Zauber", "Reise"] },
    { word: "Fullmetal Alchemist: Brotherhood", hint: "Brüder suchen den Stein der Weisen", typeHints: ["Alchemie", "Automail", "Brüder", "Sünder"] },
    { word: "Haikyuu!!", hint: "Volleyballteam einer Highschool kämpft um die Spitze", typeHints: ["Volleyball", "Karasuno", "Wing Spiker", "Netz"] },
    { word: "Hell's Paradise", hint: "Verbrecher suchen auf einer Insel nach Unsterblichkeit", typeHints: ["Gabimaru", "Tao", "Insel", "Hinata"] },
    { word: "Hellsing", hint: "Vampirjäger-Organisation gegen Untote", typeHints: ["Alucard", "Vampir", "Pistole", "Integra"] },
    { word: "Hunter x Hunter", hint: "Junge sucht seinen Vater und besteht eine Jägerprüfung", typeHints: ["Gon", "Killua", "Nen", "Chimera Ant"] },
    { word: "JoJo's Bizarre Adventure", hint: "Familie von Hamon-Nutzern und Stand-Nutzern über Generationen", typeHints: ["Stand", "Dio", "Joestar", "Pose"] },
    { word: "Jujutsu Kaisen", hint: "Schüler schluckt einen verfluchten Finger", typeHints: ["Fluch", "Sukuna", "Yuji", "Domain Expansion"] },
    { word: "Kaiju No. 8", hint: "Mann kann sich in ein riesiges Monster verwandeln", typeHints: ["Kafka", "Kaiju", "Monster", "Abwehr"] },
    { word: "Konosuba", hint: "Otaku wird in eine Fantasy-Welt reinkarniert", typeHints: ["Kazuma", "Aqua", "Megumin", "Explosion"] },
    { word: "Kuroko no Basket", hint: "Phantom-Sechster Spieler im Basketball", typeHints: ["Kuroko", "Kagami", "Basketball", "Generation der Wunder"] },
    { word: "Mashle", hint: "Magier ohne Magie nutzt reine Muskelkraft", typeHints: ["Mash", "Creme", "Muskeln", "Zauber"] },
    { word: "Mob Psycho 100", hint: "Psychisch begabter Schüler unterdrückt seine Emotionen", typeHints: ["100 Prozent", "Geister", "Reigen", "Ausbruch"] },
    { word: "Mushoku Tensei", hint: "Arbeitsloser wird als Baby in eine Fantasy-Welt wiedergeboren", typeHints: ["Rudeus", "Magie", "Reinkarnation", "Eris"] },
    { word: "My Hero Academia", hint: "Schule für junge Superhelden", typeHints: ["Quirk", "All Might", "Helden", "Schule"] },
    { word: "No Game No Life", hint: "Gaming-Geschwister erobern eine Welt die auf Spielen basiert", typeHints: ["Sora", "Shiro", "Spiele", "Disboard"] },
    { word: "One Piece", hint: "Piraten suchen den größten Schatz der Welt", typeHints: ["Strohhut", "Teufelsfrucht", "Grand Line", "Going Merry"] },
    { word: "One Punch Man", hint: "Held besiegt jeden mit einem einzigen Schlag", typeHints: ["Saitama", "Kahlkopf", "Langeweile", "Cyborg"] },
    { word: "Overlord", hint: "Spieler steckt als Skelettlord in einem MMORPG fest", typeHints: ["Ainz", "Skelett", "Nazarick", "Untote"] },
    { word: "Parasyte", hint: "Alien übernimmt die rechte Hand eines Schülers", typeHints: ["Migi", "Hand", "Shinichi", "Monster"] },
    { word: "Pokémon", hint: "Du musst sie alle fangen", typeHints: ["Pikachu", "Trainer", "Tausch", "Arena"] },
    { word: "Psycho-Pass", hint: "Polizei misst die Kriminalität von Bürgern in Echtzeit", typeHints: ["Sibyl", "Waffe", "Krimikoeffizient", "Dystopie"] },
    { word: "Re:Zero", hint: "Junger Mann kehrt nach dem Tod immer wieder zurück", typeHints: ["Subaru", "Rem", "Hexe", "Rückkehr"] },
    { word: "Rising of the Shield Hero", hint: "Mann wird mit einem Schild in eine andere Welt gerufen", typeHints: ["Naofumi", "Schild", "Raphtalia", "Verrat"] },
    { word: "Sailor Moon", hint: "Schulmädchen kämpfen gegen das Böse im Namen des Mondes", typeHints: ["Usagi", "Mond", "Kristall", "Tuxedo"] },
    { word: "Solo Leveling", hint: "Schwächster Jäger wird zum stärksten", typeHints: ["Sung Jin-Woo", "Schatten", "Dungeon", "Level"] },
    { word: "Spy x Family", hint: "Spion, Attentäter und Telepathin spielen Familie", typeHints: ["Anya", "Loid", "Hund", "Mission"] },
    { word: "Steins;Gate", hint: "Wissenschaftler verändert die Vergangenheit per Mikrowelle", typeHints: ["Zeitreise", "Mikrowelle", "D-Mail", "Okabe"] },
    { word: "Sword Art Online", hint: "Spieler stecken in einem Virtual-Reality-MMORPG fest", typeHints: ["VR", "Schwert", "Kirito", "Asuna"] },
    { word: "That Time I Got Reincarnated as a Slime", hint: "Mann wird als Schleim in eine Fantasy-Welt wiedergeboren", typeHints: ["Rimuru", "Schleim", "Tempest", "Monster"] },
    { word: "The Eminence in Shadow", hint: "Mann spielt den geheimen Strippenzieher", typeHints: ["Shadow", "Cid", "Geheim", "Illusion"] },
    { word: "The Promised Neverland", hint: "Kinder entkommen aus einem scheinbar paradiesischen Waisenhaus", typeHints: ["Emma", "Norman", "Ray", "Vertrag"] },
    { word: "The Seven Deadly Sins", hint: "Rittergruppe der verfluchten Sünden", typeHints: ["Meliodas", "Elizabeth", "Drache", "Sünden"] },
    { word: "Tokyo Ghoul", hint: "Halb Mensch, halb Fleischfresser", typeHints: ["Maske", "Kaneki", "Kaffee", "Auge"] },
    { word: "Tokyo Revengers", hint: "Mann reist in die Vergangenheit um seine Freundin zu retten", typeHints: ["Takemichi", "Toman", "Zeitsprung", "Motorrad"] },
    { word: "Undead Unluck", hint: "Mädchen bringt Unglück, Junge kann nicht sterben", typeHints: ["Fuuko", "Andy", "Negator", "Unsterblich"] },
    { word: "Vinland Saga", hint: "Wikingerjunge sucht Rache im Mittelalter", typeHints: ["Thorfinn", "Krieg", "Dänemark", "Schwert"] },
    { word: "Your Name", hint: "Zwei Teenager tauschen ihre Körper", typeHints: ["Komet", "Tasche", "Sehnsucht", "Makoto Shinkai"] },
    { word: "Yu-Gi-Oh!", hint: "Kartenkämpfe mit uralten Geistern", typeHints: ["Yugi", "Millennium", "Duell", "Dark Magician"] },
  ],
};

wordCategories["Alle Wörter"] = Object.entries(wordCategories)
  .filter(([k]) => k !== "Alle Wörter")
  .flatMap(([, v]) => v);

import { getSettings } from "./settings";

export function pickRandomWord(category: string): WordData {
  let list = wordCategories[category] ?? wordCategories.Allgemein;
  if (category === "Alle Wörter") {
    const filter = getSettings().categoryFilter;
    if (filter && filter.length > 0) {
      const filtered = filter.flatMap((c) => wordCategories[c] ?? []);
      if (filtered.length) list = filtered;
    }
  }
  return list[Math.floor(Math.random() * list.length)];
}

export function generateRoomCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "";
  for (let i = 0; i < 6; i++) code += chars[Math.floor(Math.random() * chars.length)];
  return code;
}
